In [1]:
import pandas as pd
import numpy as np
from transformers import AutoTokenizer
import torch

In [2]:
import sys
sys.path.append("./cluster_anlys")

from pca_hdbscan import run_random_pca_hdbscan_grid

seed_list = [0, 42, 1000, 9999]

In [3]:
import random

base_seed = 0
rng = random.Random(base_seed)
seed_list = rng.sample(range(2**31 - 1), 4)
seed_list

[1813382118, 827307999, 1627694678, 1911784257]

# Mistral-7B

In [4]:
model_name = "mistralai/Mistral-7B-v0.1"
# ===== Step 1: Load tokenizer =====
# tokenizer_path = f"{model_name}/tokenizer" 
# tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
# print(f"[✓] Tokenizer loaded from: {tokenizer_path}")

# ===== Step 2: Load lm_head.weight =====
space_name = "output_proj"
lm_head_path = f"{model_name}/tensors/{space_name}.pt" 
embedding_matrix = torch.load(lm_head_path, map_location="cpu")
print(f"[✓] lm_head.weight loaded: shape = {embedding_matrix.shape}")
embedding_matrix = embedding_matrix.to(torch.float32)
# embedding_matrix = embedding_matrix.cpu().to(torch.float32).numpy()
print(f"[✓] lm_head.weight loaded: shape = {embedding_matrix.shape}")

[✓] lm_head.weight loaded: shape = torch.Size([32000, 4096])
[✓] lm_head.weight loaded: shape = torch.Size([32000, 4096])

In [5]:
# =========================
# Config
# =========================

out_root = "comp"

full_pca_dim = 4096

candidate_dims = [5, 142, 997, 2084, 3031, 3459, 3938, 4088, 4096]

hdbscan_param_grid = [
    {
        "min_cluster_size": 5,
        "min_samples": 5,
        "metric": "euclidean",
        "cluster_selection_method": "eom",
        "cluster_selection_epsilon": 0.0,
    },
    # if needed
    # {
    #     "min_cluster_size": 20,
    #     "min_samples": 10,
    #     "metric": "euclidean",
    #     "cluster_selection_method": "eom",
    #     "cluster_selection_epsilon": 0.0,
    # },
]

l2_norm = True
summary_filename = f"summary.csv"

In [6]:
all_summary = []

for seed in seed_list:
    df = run_random_pca_hdbscan_grid(
        embedding_matrix=embedding_matrix,
        candidate_dims=candidate_dims,
        hdbscan_param_grid=hdbscan_param_grid,
        model_name=model_name,
        space_name=space_name,
        pca_seed=seed,
        randomized_fit_dim=full_pca_dim,
        out_root="comp",
        l2_norm=True,
    )
    all_summary.append(df)

all_summary_df = pd.concat(all_summary, ignore_index=True)
all_summary_df.head()

[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=5 seed=1813382118 time=0.87s cum_var=0.031960
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_5
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=142 seed=1813382118 time=2.18s cum_var=0.123498
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_142
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=997 seed=1813382118 time=3.65s cum_var=0.437701
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_997
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=2084 seed=1813382118 time=8.11s cum_var=0.714780
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_2084
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=3031 seed=1813382118 time=13.65s cum_var=0.884356
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_3031
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=3459 seed=1813382118 time=16.41s cum_var=0.941668
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_3459
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=3938 seed=1813382118 time=19.01s cum_var=0.990029
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_3938
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=4088 seed=1813382118 time=27.87s cum_var=0.999774
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_4088
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=4096 seed=1813382118 time=28.75s cum_var=1.000001
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_4096
Memory Cleaned.
[i] PCA mode: randomized
[i] PCA seed: 1813382118
[i] Candidate dims: [5, 142, 997, 2084, 3031, 3459, 3938, 4088, 4096]
[i] Number of HDBSCAN configs: 1
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_5
[i] PCA shape: (32000, 5)

[i] Run 00001 | pca_mode=randomized dim=5 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:27:50.494] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.44s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00001_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00001_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_142
[i] PCA shape: (32000, 142)

[i] Run 00002 | pca_mode=randomized dim=142 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:27:51.268] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.62s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00002_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00002_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_997
[i] PCA shape: (32000, 997)

[i] Run 00003 | pca_mode=randomized dim=997 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:27:52.228] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.99s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00003_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00003_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_2084
[i] PCA shape: (32000, 2084)

[i] Run 00004 | pca_mode=randomized dim=2084 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:27:53.649] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (1.49s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00004_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00004_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_3031
[i] PCA shape: (32000, 3031)

[i] Run 00005 | pca_mode=randomized dim=3031 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:27:55.660] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.00s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00005_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00005_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_3459
[i] PCA shape: (32000, 3459)

[i] Run 00006 | pca_mode=randomized dim=3459 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:27:58.216] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.23s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00006_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00006_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_3938
[i] PCA shape: (32000, 3938)

[i] Run 00007 | pca_mode=randomized dim=3938 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:28:01.004] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.49s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00007_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00007_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_4088
[i] PCA shape: (32000, 4088)

[i] Run 00008 | pca_mode=randomized dim=4088 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:28:04.028] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.41s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00008_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00008_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1813382118/pca_dim_4096
[i] PCA shape: (32000, 4096)

[i] Run 00009 | pca_mode=randomized dim=4096 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:28:06.985] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.38s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00009_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00009_meta.json

[✓] SUMMARY → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/summary_random_pca_seed_1813382118.csv
[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=5 seed=827307999 time=0.82s cum_var=0.031960
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_5
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=142 seed=827307999 time=1.97s cum_var=0.123460
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_142
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=997 seed=827307999 time=3.57s cum_var=0.437683
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_997
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=2084 seed=827307999 time=7.79s cum_var=0.714776
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_2084
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=3031 seed=827307999 time=14.45s cum_var=0.884363
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_3031
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=3459 seed=827307999 time=17.22s cum_var=0.941674
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_3459
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=3938 seed=827307999 time=17.62s cum_var=0.990040
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_3938
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=4088 seed=827307999 time=26.27s cum_var=0.999774
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_4088
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=4096 seed=827307999 time=25.55s cum_var=1.000001
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_4096
Memory Cleaned.
[i] PCA mode: randomized
[i] PCA seed: 827307999
[i] Candidate dims: [5, 142, 997, 2084, 3031, 3459, 3938, 4088, 4096]
[i] Number of HDBSCAN configs: 1
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_5
[i] PCA shape: (32000, 5)

[i] Run 00001 | pca_mode=randomized dim=5 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:13.768] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.36s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00001_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00001_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_142
[i] PCA shape: (32000, 142)

[i] Run 00002 | pca_mode=randomized dim=142 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:14.419] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.59s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00002_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00002_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_997
[i] PCA shape: (32000, 997)

[i] Run 00003 | pca_mode=randomized dim=997 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:15.337] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.94s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00003_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00003_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_2084
[i] PCA shape: (32000, 2084)

[i] Run 00004 | pca_mode=randomized dim=2084 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:16.667] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (1.43s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00004_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00004_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_3031
[i] PCA shape: (32000, 3031)

[i] Run 00005 | pca_mode=randomized dim=3031 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:18.574] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (1.92s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00005_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00005_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_3459
[i] PCA shape: (32000, 3459)

[i] Run 00006 | pca_mode=randomized dim=3459 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:21.004] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.12s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00006_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00006_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_3938
[i] PCA shape: (32000, 3938)

[i] Run 00007 | pca_mode=randomized dim=3938 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:23.646] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.35s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00007_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00007_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_4088
[i] PCA shape: (32000, 4088)

[i] Run 00008 | pca_mode=randomized dim=4088 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:26.532] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.35s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00008_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00008_meta.json
[i] Loaded PCA from: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_827307999/pca_dim_4096
[i] PCA shape: (32000, 4096)

[i] Run 00009 | pca_mode=randomized dim=4096 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:30:29.419] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.30s)
[✓] CSV  → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00009_clusters.csv
[✓] META → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00009_meta.json

[✓] SUMMARY → comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_827307999/summary_random_pca_seed_827307999.csv
[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=5 seed=1627694678 time=0.81s cum_var=0.031960
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1627694678/pca_dim_5
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=142 seed=1627694678 time=2.34s cum_var=0.123434
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1627694678/pca_dim_142
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mistral-7B-v0.1 dim=997 seed=1627694678 time=4.06s cum_var=0.437669
[✓] Saved to: comp/mistralai/Mistral-7B-v0.1/random_pca/seed_1627694678/pca_dim_997
Memory Cleaned.

,run_id,model_name,space_name,pca_mode,pca_seed,pca_source_dim,pca_dim,l2_norm,min_cluster_size,min_samples,...,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path
0,1,mistralai/Mistral-7B-v0.1,output_proj,randomized,1813382118,5,5,True,5,5,...,eom,0.0,322,27976,32000,0.874250,0.118114,0.939276,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
1,2,mistralai/Mistral-7B-v0.1,output_proj,randomized,1813382118,142,142,True,5,5,...,eom,0.0,65,28832,32000,0.901000,0.085616,0.864808,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
2,3,mistralai/Mistral-7B-v0.1,output_proj,randomized,1813382118,997,997,True,5,5,...,eom,0.0,638,24755,32000,0.773594,0.209079,0.923467,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
3,4,mistralai/Mistral-7B-v0.1,output_proj,randomized,1813382118,2084,2084,True,5,5,...,eom,0.0,886,22060,32000,0.689375,0.292843,0.942756,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
4,5,mistralai/Mistral-7B-v0.1,output_proj,randomized,1813382118,3031,3031,True,5,5,...,eom,0.0,933,21756,32000,0.679875,0.303543,0.948201,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...

# Mixtral-8x7B

In [7]:
from transformers import AutoTokenizer
import torch

model_name = "mistralai/Mixtral-8x7B-v0.1"
# ===== Step 1: Load tokenizer =====
# tokenizer_path = f"{model_name}/tokenizer" 
# tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
# print(f"[✓] Tokenizer loaded from: {tokenizer_path}")

# ===== Step 2: Load lm_head.weight =====
space_name = "output_proj"
lm_head_path = f"{model_name}/tensors/{space_name}.pt" 
embedding_matrix = torch.load(lm_head_path, map_location="cpu")
print(f"[✓] lm_head.weight loaded: shape = {embedding_matrix.shape}")
embedding_matrix = embedding_matrix.to(torch.float32)
# embedding_matrix = embedding_matrix.cpu().to(torch.float32).numpy()
print(f"[✓] lm_head.weight loaded: shape = {embedding_matrix.shape}")

[✓] lm_head.weight loaded: shape = torch.Size([32000, 4096])
[✓] lm_head.weight loaded: shape = torch.Size([32000, 4096])

In [8]:
# =========================
# Config
# =========================

out_root = "comp"

full_pca_dim = 4096

candidate_dims = [8, 158, 1111, 2156, 3052, 3457, 3957, 4093, 4096]

hdbscan_param_grid = [
    {
        "min_cluster_size": 5,
        "min_samples": 5,
        "metric": "euclidean",
        "cluster_selection_method": "eom",
        "cluster_selection_epsilon": 0.0,
    },
    # if needed
    # {
    #     "min_cluster_size": 20,
    #     "min_samples": 10,
    #     "metric": "euclidean",
    #     "cluster_selection_method": "eom",
    #     "cluster_selection_epsilon": 0.0,
    # },
]

l2_norm = True
summary_filename = f"summary.csv"

In [9]:
all_summary = []

for seed in seed_list:
    df = run_random_pca_hdbscan_grid(
        embedding_matrix=embedding_matrix,
        candidate_dims=candidate_dims,
        hdbscan_param_grid=hdbscan_param_grid,
        model_name=model_name,
        space_name=space_name,
        pca_seed=seed,
        randomized_fit_dim=full_pca_dim,
        out_root="comp",
        l2_norm=True,
    )
    all_summary.append(df)

all_summary_df = pd.concat(all_summary, ignore_index=True)
all_summary_df.head()

[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=8 seed=1813382118 time=0.91s cum_var=0.030026
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_8
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=158 seed=1813382118 time=2.04s cum_var=0.118824
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_158
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=1111 seed=1813382118 time=3.94s cum_var=0.462395
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_1111
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=2156 seed=1813382118 time=7.85s cum_var=0.727686
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_2156
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=3052 seed=1813382118 time=12.85s cum_var=0.889751
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_3052
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=3457 seed=1813382118 time=15.38s cum_var=0.944518
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_3457
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=3957 seed=1813382118 time=18.64s cum_var=0.993000
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_3957
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=4093 seed=1813382118 time=26.52s cum_var=0.999977
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_4093
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=4096 seed=1813382118 time=26.82s cum_var=1.000002
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_4096
Memory Cleaned.
[i] PCA mode: randomized
[i] PCA seed: 1813382118
[i] Candidate dims: [8, 158, 1111, 2156, 3052, 3457, 3957, 4093, 4096]
[i] Number of HDBSCAN configs: 1
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_8
[i] PCA shape: (32000, 8)

[i] Run 00001 | pca_mode=randomized dim=8 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:19.546] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.50s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00001_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00001_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_158
[i] PCA shape: (32000, 158)

[i] Run 00002 | pca_mode=randomized dim=158 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:20.325] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.57s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00002_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00002_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_1111
[i] PCA shape: (32000, 1111)

[i] Run 00003 | pca_mode=randomized dim=1111 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:21.253] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.93s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00003_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00003_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_2156
[i] PCA shape: (32000, 2156)

[i] Run 00004 | pca_mode=randomized dim=2156 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:22.628] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (1.43s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00004_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00004_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_3052
[i] PCA shape: (32000, 3052)

[i] Run 00005 | pca_mode=randomized dim=3052 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:24.560] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (1.86s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00005_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00005_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_3457
[i] PCA shape: (32000, 3457)

[i] Run 00006 | pca_mode=randomized dim=3457 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:26.926] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.09s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00006_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00006_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_3957
[i] PCA shape: (32000, 3957)

[i] Run 00007 | pca_mode=randomized dim=3957 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:29.542] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.33s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00007_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00007_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_4093
[i] PCA shape: (32000, 4093)

[i] Run 00008 | pca_mode=randomized dim=4093 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:32.410] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.37s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00008_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00008_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1813382118/pca_dim_4096
[i] PCA shape: (32000, 4096)

[i] Run 00009 | pca_mode=randomized dim=4096 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:37:35.317] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.25s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/clusters_l2=True/run_00009_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/meta_l2=True/run_00009_meta.json

[✓] SUMMARY → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/summary_random_pca_seed_1813382118.csv
[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=8 seed=827307999 time=1.04s cum_var=0.030026
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_8
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=158 seed=827307999 time=2.22s cum_var=0.118830
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_158
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=1111 seed=827307999 time=3.75s cum_var=0.462379
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_1111
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=2156 seed=827307999 time=8.10s cum_var=0.727661
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_2156
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=3052 seed=827307999 time=12.84s cum_var=0.889775
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_3052
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=3457 seed=827307999 time=15.88s cum_var=0.944519
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_3457
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=3957 seed=827307999 time=19.03s cum_var=0.992992
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_3957
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=4093 seed=827307999 time=26.08s cum_var=0.999977
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_4093
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=4096 seed=827307999 time=26.09s cum_var=1.000002
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_4096
Memory Cleaned.
[i] PCA mode: randomized
[i] PCA seed: 827307999
[i] Candidate dims: [8, 158, 1111, 2156, 3052, 3457, 3957, 4093, 4096]
[i] Number of HDBSCAN configs: 1
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_8
[i] PCA shape: (32000, 8)

[i] Run 00001 | pca_mode=randomized dim=8 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:41.832] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.50s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00001_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00001_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_158
[i] PCA shape: (32000, 158)

[i] Run 00002 | pca_mode=randomized dim=158 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:42.617] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.57s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00002_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00002_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_1111
[i] PCA shape: (32000, 1111)

[i] Run 00003 | pca_mode=randomized dim=1111 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:43.541] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (0.93s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00003_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00003_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_2156
[i] PCA shape: (32000, 2156)

[i] Run 00004 | pca_mode=randomized dim=2156 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:44.912] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (1.42s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00004_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00004_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_3052
[i] PCA shape: (32000, 3052)

[i] Run 00005 | pca_mode=randomized dim=3052 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:46.830] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (1.84s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00005_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00005_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_3457
[i] PCA shape: (32000, 3457)

[i] Run 00006 | pca_mode=randomized dim=3457 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:49.184] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.09s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00006_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00006_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_3957
[i] PCA shape: (32000, 3957)

[i] Run 00007 | pca_mode=randomized dim=3957 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:51.804] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.32s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00007_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00007_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_4093
[i] PCA shape: (32000, 4093)

[i] Run 00008 | pca_mode=randomized dim=4093 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:54.667] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.38s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00008_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00008_meta.json
[i] Loaded PCA from: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_827307999/pca_dim_4096
[i] PCA shape: (32000, 4096)

[i] Run 00009 | pca_mode=randomized dim=4096 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:39:57.580] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (2.26s)
[✓] CSV  → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/clusters_l2=True/run_00009_clusters.csv
[✓] META → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/meta_l2=True/run_00009_meta.json

[✓] SUMMARY → comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_827307999/summary_random_pca_seed_827307999.csv
[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=8 seed=1627694678 time=0.80s cum_var=0.030026
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1627694678/pca_dim_8
Memory Cleaned.
[✓] Randomized PCA finished | model=mistralai/Mixtral-8x7B-v0.1 dim=158 seed=1627694678 time=2.33s cum_var=0.118815
[✓] Saved to: comp/mistralai/Mixtral-8x7B-v0.1/random_pca/seed_1627694678/pca_dim_158
Memory Cleaned.

,run_id,model_name,space_name,pca_mode,pca_seed,pca_source_dim,pca_dim,l2_norm,min_cluster_size,min_samples,...,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path
0,1,mistralai/Mixtral-8x7B-v0.1,output_proj,randomized,1813382118,8,8,True,5,5,...,eom,0.0,92,23603,32000,0.737594,0.258043,0.983374,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
1,2,mistralai/Mixtral-8x7B-v0.1,output_proj,randomized,1813382118,158,158,True,5,5,...,eom,0.0,239,27933,32000,0.872906,0.120670,0.949454,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
2,3,mistralai/Mixtral-8x7B-v0.1,output_proj,randomized,1813382118,1111,1111,True,5,5,...,eom,0.0,962,20414,32000,0.637938,0.342022,0.944648,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
3,4,mistralai/Mixtral-8x7B-v0.1,output_proj,randomized,1813382118,2156,2156,True,5,5,...,eom,0.0,1079,19386,32000,0.605812,0.374985,0.951285,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
4,5,mistralai/Mixtral-8x7B-v0.1,output_proj,randomized,1813382118,3052,3052,True,5,5,...,eom,0.0,1093,19269,32000,0.602156,0.379665,0.954307,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...

# gpt-oss

In [10]:
model_name = "gpt-oss"
space_name = "output_proj"
# # ===== Step 1: Load tokenizer =====
# tokenizer_path = f"{model_name}/tokenizer" 
# tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
# print(f"[✓] Tokenizer loaded from: {tokenizer_path}")

# ===== Step 2: Load lm_head.weight =====
space_name = "output_proj"
lm_head_path = f"{model_name}/tensors/{space_name}.pt" 
embedding_matrix = torch.load(lm_head_path, map_location="cpu")
print(f"[✓] lm_head.weight loaded: shape = {embedding_matrix.shape}")
embedding_matrix = embedding_matrix.to(torch.float32)
# embedding_matrix = embedding_matrix.cpu().to(torch.float32).numpy()
print(f"[✓] lm_head.weight loaded: shape = {embedding_matrix.shape}")

[✓] lm_head.weight loaded: shape = torch.Size([201088, 2880])
[✓] lm_head.weight loaded: shape = torch.Size([201088, 2880])

In [11]:
# =========================
# Config
# =========================

out_root = "comp"

full_pca_dim = 2880

candidate_dims = [6, 182, 466, 739, 1591, 2264, 2532, 2868, 2880]

hdbscan_param_grid = [
    {
        "min_cluster_size": 5,
        "min_samples": 5,
        "metric": "euclidean",
        "cluster_selection_method": "eom",
        "cluster_selection_epsilon": 0.0,
    },
    # if needed
    # {
    #     "min_cluster_size": 20,
    #     "min_samples": 10,
    #     "metric": "euclidean",
    #     "cluster_selection_method": "eom",
    #     "cluster_selection_epsilon": 0.0,
    # },
]

l2_norm = True
summary_filename = f"summary.csv"

In [12]:
all_summary = []

for seed in seed_list:
    df = run_random_pca_hdbscan_grid(
        embedding_matrix=embedding_matrix,
        candidate_dims=candidate_dims,
        hdbscan_param_grid=hdbscan_param_grid,
        model_name=model_name,
        space_name=space_name,
        pca_seed=seed,
        randomized_fit_dim=full_pca_dim,
        out_root="comp",
        l2_norm=True,
    )
    all_summary.append(df)

all_summary_df = pd.concat(all_summary, ignore_index=True)
all_summary_df.head()

[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=gpt-oss dim=6 seed=1813382118 time=3.31s cum_var=0.035669
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_6
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=182 seed=1813382118 time=6.58s cum_var=0.233430
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_182
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=466 seed=1813382118 time=10.49s cum_var=0.371812
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_466
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=739 seed=1813382118 time=12.26s cum_var=0.476301
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_739
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=1591 seed=1813382118 time=30.31s cum_var=0.732096
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_1591
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2264 seed=1813382118 time=50.30s cum_var=0.890232
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2264
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2532 seed=1813382118 time=58.77s cum_var=0.944276
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2532
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2868 seed=1813382118 time=72.56s cum_var=0.999933
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2868
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2880 seed=1813382118 time=67.58s cum_var=0.999997
[✓] Saved to: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2880
Memory Cleaned.
[i] PCA mode: randomized
[i] PCA seed: 1813382118
[i] Candidate dims: [6, 182, 466, 739, 1591, 2264, 2532, 2868, 2880]
[i] Number of HDBSCAN configs: 1
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_6
[i] PCA shape: (201088, 6)

[i] Run 00001 | pca_mode=randomized dim=6 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:50:25.338] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (3.88s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00001_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00001_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_182
[i] PCA shape: (201088, 182)

[i] Run 00002 | pca_mode=randomized dim=182 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:50:29.695] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (7.65s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00002_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00002_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_466
[i] PCA shape: (201088, 466)

[i] Run 00003 | pca_mode=randomized dim=466 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:50:37.947] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (12.45s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00003_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00003_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_739
[i] PCA shape: (201088, 739)

[i] Run 00004 | pca_mode=randomized dim=739 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:50:51.171] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (17.91s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00004_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00004_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_1591
[i] PCA shape: (201088, 1591)

[i] Run 00005 | pca_mode=randomized dim=1591 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:51:10.319] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (32.95s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00005_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00005_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2264
[i] PCA shape: (201088, 2264)

[i] Run 00006 | pca_mode=randomized dim=2264 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:51:44.796] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (44.38s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00006_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00006_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2532
[i] PCA shape: (201088, 2532)

[i] Run 00007 | pca_mode=randomized dim=2532 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:52:31.069] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (51.38s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00007_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00007_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2868
[i] PCA shape: (201088, 2868)

[i] Run 00008 | pca_mode=randomized dim=2868 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:53:24.451] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (55.82s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00008_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00008_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1813382118/pca_dim_2880
[i] PCA shape: (201088, 2880)

[i] Run 00009 | pca_mode=randomized dim=2880 seed=1813382118 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 16:54:22.675] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (56.86s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_1813382118/clusters_l2=True/run_00009_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_1813382118/meta_l2=True/run_00009_meta.json

[✓] SUMMARY → comp/gpt-oss/output_proj/random/seed_1813382118/summary_random_pca_seed_1813382118.csv
[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=gpt-oss dim=6 seed=827307999 time=2.94s cum_var=0.035665
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_6
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=182 seed=827307999 time=6.40s cum_var=0.233428
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_182
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=466 seed=827307999 time=8.17s cum_var=0.371773
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_466
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=739 seed=827307999 time=12.06s cum_var=0.476302
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_739
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=1591 seed=827307999 time=32.94s cum_var=0.732085
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_1591
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2264 seed=827307999 time=50.86s cum_var=0.890246
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2264
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2532 seed=827307999 time=58.37s cum_var=0.944230
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2532
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2868 seed=827307999 time=65.26s cum_var=0.999933
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2868
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2880 seed=827307999 time=65.16s cum_var=0.999997
[✓] Saved to: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2880
Memory Cleaned.
[i] PCA mode: randomized
[i] PCA seed: 827307999
[i] Candidate dims: [6, 182, 466, 739, 1591, 2264, 2532, 2868, 2880]
[i] Number of HDBSCAN configs: 1
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_6
[i] PCA shape: (201088, 6)

[i] Run 00001 | pca_mode=randomized dim=6 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:00:49.417] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (3.62s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00001_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00001_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_182
[i] PCA shape: (201088, 182)

[i] Run 00002 | pca_mode=randomized dim=182 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:00:53.482] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (7.33s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00002_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00002_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_466
[i] PCA shape: (201088, 466)

[i] Run 00003 | pca_mode=randomized dim=466 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:01:01.414] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (12.20s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00003_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00003_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_739
[i] PCA shape: (201088, 739)

[i] Run 00004 | pca_mode=randomized dim=739 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:01:14.404] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (17.47s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00004_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00004_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_1591
[i] PCA shape: (201088, 1591)

[i] Run 00005 | pca_mode=randomized dim=1591 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:01:33.125] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (33.00s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00005_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00005_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2264
[i] PCA shape: (201088, 2264)

[i] Run 00006 | pca_mode=randomized dim=2264 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:02:07.695] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (44.31s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00006_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00006_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2532
[i] PCA shape: (201088, 2532)

[i] Run 00007 | pca_mode=randomized dim=2532 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:02:53.501] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (50.60s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00007_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00007_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2868
[i] PCA shape: (201088, 2868)

[i] Run 00008 | pca_mode=randomized dim=2868 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:03:46.148] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (57.92s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00008_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00008_meta.json
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_827307999/pca_dim_2880
[i] PCA shape: (201088, 2880)

[i] Run 00009 | pca_mode=randomized dim=2880 seed=827307999 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:04:46.023] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.
[✓] cuML HDBSCAN finished (55.72s)
[✓] CSV  → comp/gpt-oss/output_proj/random/seed_827307999/clusters_l2=True/run_00009_clusters.csv
[✓] META → comp/gpt-oss/output_proj/random/seed_827307999/meta_l2=True/run_00009_meta.json

[✓] SUMMARY → comp/gpt-oss/output_proj/random/seed_827307999/summary_random_pca_seed_827307999.csv
[warn] randomized_fit_dim is ignored in the corrected per-dim randomized PCA pipeline.
[✓] Randomized PCA finished | model=gpt-oss dim=6 seed=1627694678 time=2.96s cum_var=0.035669
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_6
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=182 seed=1627694678 time=6.64s cum_var=0.233447
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_182
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=466 seed=1627694678 time=8.51s cum_var=0.371728
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_466
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=739 seed=1627694678 time=13.24s cum_var=0.476291
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_739
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=1591 seed=1627694678 time=37.65s cum_var=0.732093
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_1591
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2264 seed=1627694678 time=52.62s cum_var=0.890229
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_2264
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2532 seed=1627694678 time=58.01s cum_var=0.944279
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_2532
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2868 seed=1627694678 time=70.44s cum_var=0.999933
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_2868
Memory Cleaned.
[✓] Randomized PCA finished | model=gpt-oss dim=2880 seed=1627694678 time=68.61s cum_var=0.999997
[✓] Saved to: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_2880
Memory Cleaned.
[i] PCA mode: randomized
[i] PCA seed: 1627694678
[i] Candidate dims: [6, 182, 466, 739, 1591, 2264, 2532, 2868, 2880]
[i] Number of HDBSCAN configs: 1
[i] Loaded PCA from: comp/gpt-oss/random_pca/seed_1627694678/pca_dim_6
[i] PCA shape: (201088, 6)

[i] Run 00001 | pca_mode=randomized dim=6 seed=1627694678 params={'min_cluster_size': 5, 'min_samples': 5, 'metric': 'euclidean', 'cluster_selection_method': 'eom', 'cluster_selection_epsilon': 0.0}
[i] HDBSCAN params | min_cluster_size=5, min_samples=5, metric=euclidean, cluster_selection_method=eom, cluster_selection_epsilon=0.0
[2026-03-26 17:11:28.060] [CUML] [warning] Using data on device memory because knn_n_clusters = 1.

,run_id,model_name,space_name,pca_mode,pca_seed,pca_source_dim,pca_dim,l2_norm,min_cluster_size,min_samples,...,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path
0,1,gpt-oss,output_proj,randomized,1813382118,6,6,True,5,5,...,eom,0.0,1198,149829,201088,0.745092,0.250480,0.982626,comp/gpt-oss/output_proj/random/seed_181338211...,comp/gpt-oss/output_proj/random/seed_181338211...
1,2,gpt-oss,output_proj,randomized,1813382118,182,182,True,5,5,...,eom,0.0,738,169654,201088,0.843680,0.147158,0.941392,comp/gpt-oss/output_proj/random/seed_181338211...,comp/gpt-oss/output_proj/random/seed_181338211...
2,3,gpt-oss,output_proj,randomized,1813382118,466,466,True,5,5,...,eom,0.0,1918,169215,201088,0.841497,0.153696,0.969675,comp/gpt-oss/output_proj/random/seed_181338211...,comp/gpt-oss/output_proj/random/seed_181338211...
3,4,gpt-oss,output_proj,randomized,1813382118,739,739,True,5,5,...,eom,0.0,2769,155544,201088,0.773512,0.218618,0.965252,comp/gpt-oss/output_proj/random/seed_181338211...,comp/gpt-oss/output_proj/random/seed_181338211...
4,5,gpt-oss,output_proj,randomized,1813382118,1591,1591,True,5,5,...,eom,0.0,3610,136401,201088,0.678315,0.306931,0.954135,comp/gpt-oss/output_proj/random/seed_181338211...,comp/gpt-oss/output_proj/random/seed_181338211...