# Random Orthogonal Projection and HDBSCAN Control

Generate one full orthogonal basis per model and seed, then use nested slices at the nine baseline dimensions.

In [7]:
import gc
import sys

import torch

sys.path.append("./cluster_anlys")

from random_projection import (
    DEFAULT_SEEDS,
    MODEL_CONFIGS,
    aggregate_random_projection_seed_summaries,
    run_random_projection_hdbscan_grid,
)

In [8]:
OUT_ROOT = "comp"
SPACE_NAME = "output_proj"
SEED_LIST = list(DEFAULT_SEEDS)
ROW_BATCH_SIZE = 4096

HDBSCAN_CONFIG = {
    "l2_norm": True,
    "min_cluster_size": 5,
    "min_samples": 5,
    "metric": "euclidean",
    "cluster_selection_method": "eom",
    "cluster_selection_epsilon": 0.0,
}

In [9]:
def run_model_random_projection_control(model_key):
    model_config = MODEL_CONFIGS[model_key]
    model_name = model_config["model_name"]
    candidate_dims = model_config["candidate_dims"]
    tensor_path = f"{model_name}/tensors/{SPACE_NAME}.pt"

    embedding_matrix = torch.load(tensor_path, map_location="cpu")
    embedding_matrix = embedding_matrix.to(torch.float32)
    print(f"Loaded {model_name}: {tuple(embedding_matrix.shape)}")

    seed_summaries = {}
    for rp_seed in SEED_LIST:
        seed_summaries[int(rp_seed)] = run_random_projection_hdbscan_grid(
            embedding_matrix=embedding_matrix,
            candidate_dims=candidate_dims,
            model_name=model_name,
            space_name=SPACE_NAME,
            rp_seed=int(rp_seed),
            out_root=OUT_ROOT,
            row_batch_size=ROW_BATCH_SIZE,
            reuse_complete=True,
            **HDBSCAN_CONFIG,
        )

    all_seed_summary_df = aggregate_random_projection_seed_summaries(
        out_root=OUT_ROOT,
        model_name=model_name,
        space_name=SPACE_NAME,
        seed_list=SEED_LIST,
    )

    del embedding_matrix
    gc.collect()
    return seed_summaries, all_seed_summary_df

## Mistral-7B

In [10]:
mistral_rp_seed_summaries, mistral_rp_all_seed_df = (
    run_model_random_projection_control("mistral")
)
mistral_rp_all_seed_df.head()

Loaded mistralai/Mistral-7B-v0.1: (32000, 4096)
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_2073320061/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1097954097/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1043521778/summary.csv

,run_id,model_name,space_name,projection_mode,rp_seed,pca_dim,l2_norm,min_cluster_size,min_samples,metric,...,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,mean_cluster_size,median_cluster_size,cluster_csv_path,meta_json_path
0,1,mistralai/Mistral-7B-v0.1,output_proj,random_projection,86939546,5,True,5,5,euclidean,...,726,23160,32000,0.723750,0.268009,0.970169,12.176309,9.0,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
1,2,mistralai/Mistral-7B-v0.1,output_proj,random_projection,86939546,142,True,5,5,euclidean,...,742,24697,32000,0.771781,0.218271,0.956410,9.842318,8.0,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
2,3,mistralai/Mistral-7B-v0.1,output_proj,random_projection,86939546,997,True,5,5,euclidean,...,952,21240,32000,0.663750,0.321505,0.956149,11.302521,9.0,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
3,4,mistralai/Mistral-7B-v0.1,output_proj,random_projection,86939546,2084,True,5,5,euclidean,...,969,20885,32000,0.652656,0.332320,0.956748,11.470588,9.0,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...
4,5,mistralai/Mistral-7B-v0.1,output_proj,random_projection,86939546,3031,True,5,5,euclidean,...,966,20814,32000,0.650438,0.334804,0.957780,11.579710,9.0,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/ran...

## Mixtral-8x7B

In [11]:
mixtral_rp_seed_summaries, mixtral_rp_all_seed_df = (
    run_model_random_projection_control("mixtral")
)
mixtral_rp_all_seed_df.head()

Loaded mistralai/Mixtral-8x7B-v0.1: (32000, 4096)
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_1813382118/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_827307999/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_1627694678/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_1911784257/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_903170602/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_86939546/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_556019485/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_2073320061/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_1097954097/summary.csv
Reusing complete random-projection summary: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/seed_1043521778/summary.csv

,run_id,model_name,space_name,projection_mode,rp_seed,pca_dim,l2_norm,min_cluster_size,min_samples,metric,...,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,mean_cluster_size,median_cluster_size,cluster_csv_path,meta_json_path
0,1,mistralai/Mixtral-8x7B-v0.1,output_proj,random_projection,86939546,8,True,5,5,euclidean,...,442,27169,32000,0.849031,0.148122,0.981146,10.929864,8.0,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
1,2,mistralai/Mixtral-8x7B-v0.1,output_proj,random_projection,86939546,158,True,5,5,euclidean,...,981,21668,32000,0.677125,0.310978,0.963152,10.532110,9.0,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
2,3,mistralai/Mixtral-8x7B-v0.1,output_proj,random_projection,86939546,1111,True,5,5,euclidean,...,1090,19358,32000,0.604938,0.378874,0.959023,11.598165,9.0,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
3,4,mistralai/Mixtral-8x7B-v0.1,output_proj,random_projection,86939546,2156,True,5,5,euclidean,...,1083,19163,32000,0.598844,0.384487,0.958446,11.853186,9.0,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...
4,5,mistralai/Mixtral-8x7B-v0.1,output_proj,random_projection,86939546,3052,True,5,5,euclidean,...,1088,19026,32000,0.594562,0.388794,0.958948,11.924632,9.0,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/r...

## gpt-oss-20B

In [12]:
gpt_oss_rp_seed_summaries, gpt_oss_rp_all_seed_df = (
    run_model_random_projection_control("gpt-oss")
)
gpt_oss_rp_all_seed_df.head()

Loaded gpt-oss: (201088, 2880)
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_1813382118/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_827307999/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_1627694678/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_1911784257/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_903170602/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_86939546/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_556019485/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_2073320061/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_1097954097/summary.csv
Reusing complete random-projection summary: comp/gpt-oss/output_proj/random_projection/seed_1043521778/summary.csv

,run_id,model_name,space_name,projection_mode,rp_seed,pca_dim,l2_norm,min_cluster_size,min_samples,metric,...,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,mean_cluster_size,median_cluster_size,cluster_csv_path,meta_json_path
0,1,gpt-oss,output_proj,random_projection,86939546,6,True,5,5,euclidean,...,3639,160012,201088,0.795731,0.200928,0.983646,11.287716,8.0,comp/gpt-oss/output_proj/random_projection/see...,comp/gpt-oss/output_proj/random_projection/see...
1,2,gpt-oss,output_proj,random_projection,86939546,182,True,5,5,euclidean,...,3385,141315,201088,0.702752,0.282852,0.951568,17.658198,12.0,comp/gpt-oss/output_proj/random_projection/see...,comp/gpt-oss/output_proj/random_projection/see...
2,3,gpt-oss,output_proj,random_projection,86939546,466,True,5,5,euclidean,...,3667,134430,201088,0.668513,0.315336,0.951277,18.177802,13.0,comp/gpt-oss/output_proj/random_projection/see...,comp/gpt-oss/output_proj/random_projection/see...
3,4,gpt-oss,output_proj,random_projection,86939546,739,True,5,5,euclidean,...,3792,132912,201088,0.660964,0.322495,0.951212,17.978903,13.0,comp/gpt-oss/output_proj/random_projection/see...,comp/gpt-oss/output_proj/random_projection/see...
4,5,gpt-oss,output_proj,random_projection,86939546,1591,True,5,5,euclidean,...,3847,132124,201088,0.657046,0.326200,0.951147,17.926696,13.0,comp/gpt-oss/output_proj/random_projection/see...,comp/gpt-oss/output_proj/random_projection/see...

In [13]:
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display


def canonicalize_cluster_partition(token_ids, cluster_ids):
    token_ids = np.asarray(token_ids, dtype=np.int64)
    cluster_ids = np.asarray(cluster_ids, dtype=np.int64)
    canonical_ids = np.full(cluster_ids.shape, -1, dtype=np.int64)
    assigned = cluster_ids >= 0
    if assigned.any():
        assigned_tokens = pd.Series(token_ids[assigned])
        assigned_clusters = pd.Series(cluster_ids[assigned])
        canonical_ids[assigned] = (
            assigned_tokens.groupby(assigned_clusters, sort=False).transform("min")
        ).to_numpy(dtype=np.int64)
    return canonical_ids


def check_full_dimension_hdbscan_invariance(model_key):
    model_config = MODEL_CONFIGS[model_key]
    model_name = model_config["model_name"]
    full_dimension = int(max(model_config["candidate_dims"]))
    model_root = Path(OUT_ROOT) / model_name / SPACE_NAME
    baseline_summary_path = model_root / "summary.csv"
    baseline_summary = pd.read_csv(baseline_summary_path)
    baseline_rows = baseline_summary.loc[
        baseline_summary["pca_dim"].astype(int) == full_dimension
    ]
    if len(baseline_rows) != 1:
        raise ValueError(
            f"Expected one baseline row at dim={full_dimension}, "
            f"found {len(baseline_rows)}"
        )

    baseline_row = baseline_rows.iloc[0]
    baseline_clusters = pd.read_csv(
        Path(baseline_row["cluster_csv_path"]),
        usecols=["token_id", "cluster_id", "probability"],
    ).sort_values("token_id").reset_index(drop=True)
    if baseline_clusters["token_id"].duplicated().any():
        raise ValueError("Baseline cluster output contains duplicate token IDs")

    baseline_token_ids = baseline_clusters["token_id"].to_numpy(dtype=np.int64)
    baseline_cluster_ids = baseline_clusters["cluster_id"].to_numpy(dtype=np.int64)
    baseline_probabilities = baseline_clusters["probability"].to_numpy(dtype=np.float64)
    baseline_canonical_ids = canonicalize_cluster_partition(
        baseline_token_ids, baseline_cluster_ids
    )

    records = []
    for rp_seed in SEED_LIST:
        seed_summary_path = (
            model_root
            / "random_projection"
            / f"seed_{int(rp_seed)}"
            / "summary.csv"
        )
        if not seed_summary_path.exists():
            records.append(
                {
                    "model_name": model_name,
                    "rp_seed": int(rp_seed),
                    "full_dimension": full_dimension,
                    "status": "seed_summary_missing",
                }
            )
            continue

        seed_summary = pd.read_csv(seed_summary_path)
        seed_rows = seed_summary.loc[
            seed_summary["pca_dim"].astype(int) == full_dimension
        ]
        if len(seed_rows) != 1:
            records.append(
                {
                    "model_name": model_name,
                    "rp_seed": int(rp_seed),
                    "full_dimension": full_dimension,
                    "status": "full_dimension_result_missing",
                }
            )
            continue

        seed_row = seed_rows.iloc[0]
        projected_clusters = pd.read_csv(
            Path(seed_row["cluster_csv_path"]),
            usecols=["token_id", "cluster_id", "probability"],
        ).sort_values("token_id").reset_index(drop=True)
        if projected_clusters["token_id"].duplicated().any():
            raise ValueError(
                f"Random-projection output contains duplicate token IDs for seed={rp_seed}"
            )

        projected_token_ids = projected_clusters["token_id"].to_numpy(dtype=np.int64)
        token_ids_exact = np.array_equal(baseline_token_ids, projected_token_ids)
        if not token_ids_exact:
            records.append(
                {
                    "model_name": model_name,
                    "rp_seed": int(rp_seed),
                    "full_dimension": full_dimension,
                    "status": "token_ids_mismatch",
                    "token_ids_exact": False,
                }
            )
            continue

        projected_cluster_ids = projected_clusters["cluster_id"].to_numpy(
            dtype=np.int64
        )
        projected_probabilities = projected_clusters["probability"].to_numpy(
            dtype=np.float64
        )
        projected_canonical_ids = canonicalize_cluster_partition(
            projected_token_ids, projected_cluster_ids
        )
        partition_mismatch_count = int(
            np.count_nonzero(baseline_canonical_ids != projected_canonical_ids)
        )
        noise_mismatch_count = int(
            np.count_nonzero(
                (baseline_cluster_ids == -1) != (projected_cluster_ids == -1)
            )
        )
        probability_difference = np.abs(
            baseline_probabilities - projected_probabilities
        )
        records.append(
            {
                "model_name": model_name,
                "rp_seed": int(rp_seed),
                "full_dimension": full_dimension,
                "status": "checked",
                "token_ids_exact": True,
                "partition_exact_up_to_label_permutation": (
                    partition_mismatch_count == 0
                ),
                "partition_mismatch_count": partition_mismatch_count,
                "noise_assignment_mismatch_count": noise_mismatch_count,
                "baseline_cluster_count": int(
                    baseline_row["n_clusters_excl_noise"]
                ),
                "projected_cluster_count": int(
                    seed_row["n_clusters_excl_noise"]
                ),
                "baseline_noise_count": int(baseline_row["n_noise"]),
                "projected_noise_count": int(seed_row["n_noise"]),
                "probabilities_exact": np.array_equal(
                    baseline_probabilities,
                    projected_probabilities,
                    equal_nan=True,
                ),
                "max_probability_abs_difference": float(
                    np.nanmax(probability_difference)
                ),
            }
        )

    result = pd.DataFrame(records)
    output_path = (
        model_root
        / "random_projection"
        / "full_dimension_invariance_check.csv"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(output_path, index=False)
    checked = result.loc[result["status"] == "checked"]
    all_partitions_exact = bool(
        len(checked) == len(SEED_LIST)
        and checked["partition_exact_up_to_label_permutation"].all()
    )
    print(f"{model_name}: all full-dimensional partitions exact = {all_partitions_exact}")
    print(f"Saved invariance check: {output_path}")
    return result

In [14]:
mistral_full_dimension_check = check_full_dimension_hdbscan_invariance("mistral")
display(mistral_full_dimension_check)

mistralai/Mistral-7B-v0.1: all full-dimensional partitions exact = False
Saved invariance check: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/full_dimension_invariance_check.csv

,model_name,rp_seed,full_dimension,status,token_ids_exact,partition_exact_up_to_label_permutation,partition_mismatch_count,noise_assignment_mismatch_count,baseline_cluster_count,projected_cluster_count,baseline_noise_count,projected_noise_count,probabilities_exact,max_probability_abs_difference
0,mistralai/Mistral-7B-v0.1,1813382118,4096,checked,True,False,284,271,983,982,21395,21132,False,1.0
1,mistralai/Mistral-7B-v0.1,827307999,4096,checked,True,False,284,277,983,981,21395,21136,False,1.0
2,mistralai/Mistral-7B-v0.1,1627694678,4096,checked,True,False,281,274,983,982,21395,21127,False,1.0
3,mistralai/Mistral-7B-v0.1,1911784257,4096,checked,True,False,291,277,983,981,21395,21140,False,1.0
4,mistralai/Mistral-7B-v0.1,903170602,4096,checked,True,False,281,274,983,983,21395,21123,False,1.0
5,mistralai/Mistral-7B-v0.1,86939546,4096,checked,True,False,276,269,983,982,21395,21134,False,1.0
6,mistralai/Mistral-7B-v0.1,556019485,4096,checked,True,False,284,276,983,981,21395,21135,False,1.0
7,mistralai/Mistral-7B-v0.1,2073320061,4096,checked,True,False,291,271,983,984,21395,21134,False,1.0
8,mistralai/Mistral-7B-v0.1,1097954097,4096,checked,True,False,280,272,983,982,21395,21129,False,1.0
9,mistralai/Mistral-7B-v0.1,1043521778,4096,checked,True,False,277,269,983,982,21395,21130,False,1.0

In [15]:
mixtral_full_dimension_check = check_full_dimension_hdbscan_invariance("mixtral")
display(mixtral_full_dimension_check)

mistralai/Mixtral-8x7B-v0.1: all full-dimensional partitions exact = False
Saved invariance check: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/full_dimension_invariance_check.csv

,model_name,rp_seed,full_dimension,status,token_ids_exact,partition_exact_up_to_label_permutation,partition_mismatch_count,noise_assignment_mismatch_count,baseline_cluster_count,projected_cluster_count,baseline_noise_count,projected_noise_count,probabilities_exact,max_probability_abs_difference
0,mistralai/Mixtral-8x7B-v0.1,1813382118,4096,checked,True,False,30,15,1091,1093,19042,19037,False,1.0
1,mistralai/Mixtral-8x7B-v0.1,827307999,4096,checked,True,False,27,27,1091,1093,19042,19031,False,1.0
2,mistralai/Mixtral-8x7B-v0.1,1627694678,4096,checked,True,False,28,20,1091,1094,19042,19026,False,1.0
3,mistralai/Mixtral-8x7B-v0.1,1911784257,4096,checked,True,False,20,11,1091,1092,19042,19035,False,1.0
4,mistralai/Mixtral-8x7B-v0.1,903170602,4096,checked,True,False,17,9,1091,1092,19042,19039,False,1.0
5,mistralai/Mixtral-8x7B-v0.1,86939546,4096,checked,True,False,30,21,1091,1091,19042,19043,False,1.0
6,mistralai/Mixtral-8x7B-v0.1,556019485,4096,checked,True,False,18,10,1091,1092,19042,19036,False,1.0
7,mistralai/Mixtral-8x7B-v0.1,2073320061,4096,checked,True,False,22,14,1091,1092,19042,19036,False,1.0
8,mistralai/Mixtral-8x7B-v0.1,1097954097,4096,checked,True,False,22,14,1091,1092,19042,19042,False,1.0
9,mistralai/Mixtral-8x7B-v0.1,1043521778,4096,checked,True,False,21,13,1091,1092,19042,19035,False,1.0

In [16]:
gpt_oss_full_dimension_check = check_full_dimension_hdbscan_invariance("gpt-oss")
display(gpt_oss_full_dimension_check)

gpt-oss: all full-dimensional partitions exact = False
Saved invariance check: comp/gpt-oss/output_proj/random_projection/full_dimension_invariance_check.csv

,model_name,rp_seed,full_dimension,status,token_ids_exact,partition_exact_up_to_label_permutation,partition_mismatch_count,noise_assignment_mismatch_count,baseline_cluster_count,projected_cluster_count,baseline_noise_count,projected_noise_count,probabilities_exact,max_probability_abs_difference
0,gpt-oss,1813382118,2880,checked,True,False,110,25,3880,3877,132271,132274,False,1.0
1,gpt-oss,827307999,2880,checked,True,False,37,29,3880,3877,132271,132280,False,1.0
2,gpt-oss,1627694678,2880,checked,True,False,27,26,3880,3877,132271,132281,False,1.0
3,gpt-oss,1911784257,2880,checked,True,False,22,22,3880,3878,132271,132277,False,1.0
4,gpt-oss,903170602,2880,checked,True,False,42,28,3880,3877,132271,132283,False,1.0
5,gpt-oss,86939546,2880,checked,True,False,57,29,3880,3877,132271,132290,False,1.0
6,gpt-oss,556019485,2880,checked,True,False,41,34,3880,3878,132271,132283,False,1.0
7,gpt-oss,2073320061,2880,checked,True,False,80,25,3880,3877,132271,132276,False,1.0
8,gpt-oss,1097954097,2880,checked,True,False,37,30,3880,3878,132271,132277,False,1.0
9,gpt-oss,1043521778,2880,checked,True,False,33,27,3880,3877,132271,132290,False,1.0

In [17]:
from sklearn.metrics import adjusted_mutual_info_score, adjusted_rand_score


def calculate_full_dimension_ami_ari(model_key):
    model_config = MODEL_CONFIGS[model_key]
    model_name = model_config["model_name"]
    full_dimension = int(max(model_config["candidate_dims"]))
    model_root = Path(OUT_ROOT) / model_name / SPACE_NAME

    baseline_summary = pd.read_csv(model_root / "summary.csv")
    baseline_rows = baseline_summary.loc[
        baseline_summary["pca_dim"].astype(int) == full_dimension
    ]
    if len(baseline_rows) != 1:
        raise ValueError(
            f"Expected one baseline row at dim={full_dimension}, "
            f"found {len(baseline_rows)}"
        )

    baseline_clusters = pd.read_csv(
        Path(baseline_rows.iloc[0]["cluster_csv_path"]),
        usecols=["token_id", "cluster_id"],
    ).sort_values("token_id").reset_index(drop=True)
    baseline_token_ids = baseline_clusters["token_id"].to_numpy(dtype=np.int64)
    baseline_labels = baseline_clusters["cluster_id"].to_numpy(dtype=np.int64)

    records = []
    for rp_seed in SEED_LIST:
        seed_summary_path = (
            model_root
            / "random_projection"
            / f"seed_{int(rp_seed)}"
            / "summary.csv"
        )
        if not seed_summary_path.exists():
            records.append(
                {
                    "model_name": model_name,
                    "rp_seed": int(rp_seed),
                    "full_dimension": full_dimension,
                    "status": "seed_summary_missing",
                }
            )
            continue

        seed_summary = pd.read_csv(seed_summary_path)
        seed_rows = seed_summary.loc[
            seed_summary["pca_dim"].astype(int) == full_dimension
        ]
        if len(seed_rows) != 1:
            records.append(
                {
                    "model_name": model_name,
                    "rp_seed": int(rp_seed),
                    "full_dimension": full_dimension,
                    "status": "full_dimension_result_missing",
                }
            )
            continue

        projected_clusters = pd.read_csv(
            Path(seed_rows.iloc[0]["cluster_csv_path"]),
            usecols=["token_id", "cluster_id"],
        ).sort_values("token_id").reset_index(drop=True)
        projected_token_ids = projected_clusters["token_id"].to_numpy(
            dtype=np.int64
        )
        if not np.array_equal(baseline_token_ids, projected_token_ids):
            records.append(
                {
                    "model_name": model_name,
                    "rp_seed": int(rp_seed),
                    "full_dimension": full_dimension,
                    "status": "token_ids_mismatch",
                }
            )
            continue

        projected_labels = projected_clusters["cluster_id"].to_numpy(
            dtype=np.int64
        )
        records.append(
            {
                "model_name": model_name,
                "rp_seed": int(rp_seed),
                "full_dimension": full_dimension,
                "status": "checked",
                "n_tokens": int(len(baseline_labels)),
                "ari": float(
                    adjusted_rand_score(baseline_labels, projected_labels)
                ),
                "ami": float(
                    adjusted_mutual_info_score(
                        baseline_labels,
                        projected_labels,
                        average_method="arithmetic",
                    )
                ),
            }
        )

    result = pd.DataFrame(records)
    output_path = (
        model_root
        / "random_projection"
        / "full_dimension_ami_ari.csv"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(output_path, index=False)
    print(f"Saved full-dimensional AMI/ARI check: {output_path}")
    return result

In [18]:
mistral_full_dimension_ami_ari = calculate_full_dimension_ami_ari("mistral")
display(mistral_full_dimension_ami_ari)

Saved full-dimensional AMI/ARI check: comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/full_dimension_ami_ari.csv

,model_name,rp_seed,full_dimension,status,n_tokens,ari,ami
0,mistralai/Mistral-7B-v0.1,1813382118,4096,checked,32000,0.977213,0.987823
1,mistralai/Mistral-7B-v0.1,827307999,4096,checked,32000,0.976712,0.987499
2,mistralai/Mistral-7B-v0.1,1627694678,4096,checked,32000,0.976961,0.987575
3,mistralai/Mistral-7B-v0.1,1911784257,4096,checked,32000,0.976712,0.987387
4,mistralai/Mistral-7B-v0.1,903170602,4096,checked,32000,0.976960,0.987747
5,mistralai/Mistral-7B-v0.1,86939546,4096,checked,32000,0.977380,0.988062
6,mistralai/Mistral-7B-v0.1,556019485,4096,checked,32000,0.976795,0.987504
7,mistralai/Mistral-7B-v0.1,2073320061,4096,checked,32000,0.977213,0.987775
8,mistralai/Mistral-7B-v0.1,1097954097,4096,checked,32000,0.977128,0.987714
9,mistralai/Mistral-7B-v0.1,1043521778,4096,checked,32000,0.977380,0.988012

In [19]:
mixtral_full_dimension_ami_ari = calculate_full_dimension_ami_ari("mixtral")
display(mixtral_full_dimension_ami_ari)

Saved full-dimensional AMI/ARI check: comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random_projection/full_dimension_ami_ari.csv

,model_name,rp_seed,full_dimension,status,n_tokens,ari,ami
0,mistralai/Mixtral-8x7B-v0.1,1813382118,4096,checked,32000,0.998780,0.998714
1,mistralai/Mixtral-8x7B-v0.1,827307999,4096,checked,32000,0.997806,0.998275
2,mistralai/Mixtral-8x7B-v0.1,1627694678,4096,checked,32000,0.998375,0.998722
3,mistralai/Mixtral-8x7B-v0.1,1911784257,4096,checked,32000,0.999106,0.999153
4,mistralai/Mixtral-8x7B-v0.1,903170602,4096,checked,32000,0.999268,0.999365
5,mistralai/Mixtral-8x7B-v0.1,86939546,4096,checked,32000,0.998293,0.998480
6,mistralai/Mixtral-8x7B-v0.1,556019485,4096,checked,32000,0.999187,0.999283
7,mistralai/Mixtral-8x7B-v0.1,2073320061,4096,checked,32000,0.998862,0.998926
8,mistralai/Mixtral-8x7B-v0.1,1097954097,4096,checked,32000,0.998862,0.998928
9,mistralai/Mixtral-8x7B-v0.1,1043521778,4096,checked,32000,0.998943,0.999025

In [20]:
gpt_oss_full_dimension_ami_ari = calculate_full_dimension_ami_ari("gpt-oss")
display(gpt_oss_full_dimension_ami_ari)

Saved full-dimensional AMI/ARI check: comp/gpt-oss/output_proj/random_projection/full_dimension_ami_ari.csv

,model_name,rp_seed,full_dimension,status,n_tokens,ari,ami
0,gpt-oss,1813382118,2880,checked,201088,0.999667,0.999654
1,gpt-oss,827307999,2880,checked,201088,0.999614,0.999623
2,gpt-oss,1627694678,2880,checked,201088,0.999654,0.999670
3,gpt-oss,1911784257,2880,checked,201088,0.999707,0.999711
4,gpt-oss,903170602,2880,checked,201088,0.999627,0.999644
5,gpt-oss,86939546,2880,checked,201088,0.999614,0.999629
6,gpt-oss,556019485,2880,checked,201088,0.999547,0.999517
7,gpt-oss,2073320061,2880,checked,201088,0.999667,0.999654
8,gpt-oss,1097954097,2880,checked,201088,0.999600,0.999583
9,gpt-oss,1043521778,2880,checked,201088,0.999640,0.999660