In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import torch
from pathlib import Path
from transformers import AutoTokenizer

In [2]:
import sys
import pandas as pd

sys.path.append("./cluster_anlys")

from script_entropy import (
    run_script_entropy_over_pca_dims,
    save_batch_summary_df,
    save_single_partition_outputs, 
    run_script_entropy_over_random_pca_dims
)
seed_list = [0, 42, 1000, 9999, 1813382118, 827307999, 1627694678, 1911784257]

In [3]:
seed_list= [1813382118, 827307999, 1627694678, 1911784257]

In [4]:
seed_list = [1813382118,
 827307999,
 1627694678,
 1911784257,
 903170602,
 86939546,
 556019485,
 2073320061,
 1097954097,
 1043521778]

In [5]:
from script_entropy import sanity_check_words
sanity_check_words()

   token_str    script
0   shoulder     Latin
1  shoulders     Latin
2       homb     Latin
3   Shoulder     Latin
4          肩       Han
5   Schulter     Latin
6       плеч  Cyrillic

In [6]:
from script_entropy import toy_partition_test
toy_partition_test()

{'token_df':    cluster_id  token_str    script
 0           0   shoulder     Latin
 1           0  shoulders     Latin
 2           0   Schulter     Latin
 3           1          肩       Han
 4           1       плеч  Cyrillic
 5           1          肩       Han,
 'global_script_set': ['Han', 'Latin', 'Cyrillic'],
 'cluster_entropy_df':    cluster_id  Han  Latin  Cyrillic         H   H_norm
 0           0    0      3         0  0.000000  0.00000
 1           1    2      0         1  0.636514  0.57938,
 'partition_stats': {'num_clusters': 2,
  'mean_H': 0.3182570841474064,
  'std_H': 0.3182570841474064,
  'mean_H_norm': 0.28969008214284747,
  'std_H_norm': 0.28969008214284747}}

# Mistral-7B

In [5]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "permutation/mistralai/Mistral-7B-v0.1_rand"
space_name = "output_proj"

# out_root = "comp"
# model_name = "mistralai/Mistral-7B-v0.1"
# space_name = "output_proj"

# ===== Step 1: Load tokenizer =====
tokenizer_path = f"mistralai/Mistral-7B-v0.1/tokenizer" 
tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
print(f"[✓] Tokenizer loaded from: {tokenizer_path}")


l2_norm = True
min_cluster_size = 5
min_samples = 5
metric = "euclidean"
cluster_selection_method = "eom"
cluster_selection_epsilon = 0.0

token_col = "token_str"
cluster_id_col = "cluster_id"

pca_dim_list = [5, 142, 997, 2084, 3031, 3459, 3938, 4088, 4096]

[✓] Tokenizer loaded from: mistralai/Mistral-7B-v0.1/tokenizer

In [23]:
batch_result = run_script_entropy_over_pca_dims(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    pca_dim_list=pca_dim_list,
    l2_norm=l2_norm,
    min_cluster_size=min_cluster_size,
    min_samples=min_samples,
    metric=metric,
    cluster_selection_method=cluster_selection_method,
    cluster_selection_epsilon=cluster_selection_epsilon,
    tokenizer=tokenizer,
    print_columns_first_only=True,
)

=== Running script entropy: pca_dim=5 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running script entropy: pca_dim=142 ===

=== Running script entropy: pca_dim=997 ===

=== Running script entropy: pca_dim=2084 ===

=== Running script entropy: pca_dim=3031 ===

=== Running script entropy: pca_dim=3459 ===

=== Running script entropy: pca_dim=3938 ===

=== Running script entropy: pca_dim=4088 ===

=== Running script entropy: pca_dim=4096 ===

In [24]:
script_entropy_summary_df = batch_result["summary_df"]
script_entropy_summary_df

,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,num_clusters,mean_H,std_H,mean_H_norm,std_H_norm
0,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,5,True,5,5,euclidean,eom,0.0,308,0.610141,0.379330,0.179390,0.111529
1,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,142,True,5,5,euclidean,eom,0.0,79,0.665518,0.331315,0.195672,0.097411
2,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,997,True,5,5,euclidean,eom,0.0,647,0.336386,0.289297,0.098902,0.085058
3,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,2084,True,5,5,euclidean,eom,0.0,883,0.294845,0.279421,0.086689,0.082154
4,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,3031,True,5,5,euclidean,eom,0.0,939,0.272574,0.253633,0.080141,0.074572
5,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,3459,True,5,5,euclidean,eom,0.0,953,0.212307,0.243119,0.062421,0.071480
6,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,3938,True,5,5,euclidean,eom,0.0,968,0.217885,0.246662,0.064061,0.072522
7,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,4088,True,5,5,euclidean,eom,0.0,971,0.256249,0.254856,0.075341,0.074931
8,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,4096,True,5,5,euclidean,eom,0.0,983,0.234775,0.250511,0.069027,0.073654

In [7]:
script_entropy_summary_df = batch_result["summary_df"]

summary_outpath = (
    f"{out_root}/{model_name}/{space_name}/"
    "script_entropy_summary.csv"
)

script_entropy_summary_df.to_csv(summary_outpath, index=False)
print(f"Saved batch summary -> {summary_outpath}")

Saved batch summary -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/script_entropy_summary.csv

In [20]:
from script_entropy import save_single_partition_outputs

for pca_dim, result in batch_result["per_partition_results"].items():
    out_dir = (
        f"{out_root}/{model_name}/{space_name}/"
        f"script_entropy/pca_{pca_dim}"
    )

    save_single_partition_outputs(
        result=result,
        out_dir=out_dir,
    )

Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/script_entropy/pca_2880/partition_script_entropy_summary.json

### Random

In [21]:
script_entropy_summary_all = []

for pca_seed in seed_list:
    print(f"\n===== Running seed {pca_seed} =====")

    batch_result = run_script_entropy_over_random_pca_dims(
        out_root=out_root,
        model_name=model_name,
        space_name=space_name,
        pca_seed=pca_seed,
        pca_dim_list=pca_dim_list,
        l2_norm=l2_norm,
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        metric=metric,
        cluster_selection_method=cluster_selection_method,
        cluster_selection_epsilon=cluster_selection_epsilon,
        tokenizer=tokenizer,
        print_columns_first_only=True,
    )

    script_entropy_summary_df = batch_result["summary_df"]
    script_entropy_summary_all.append(script_entropy_summary_df)


    for pca_dim, result in batch_result["per_partition_results"].items():
        out_dir = (
            f"{out_root}/{model_name}/{space_name}/"
            f"random/seed_{pca_seed}/"
            f"script_entropy/pca_{pca_dim}"
        )

        save_single_partition_outputs(
            result=result,
            out_dir=out_dir,
        )

    summary_outpath = (
        f"{out_root}/{model_name}/{space_name}/"
        f"random/seed_{pca_seed}/"
        f"summary_random_pca_seed_{pca_seed}_script_entropy.csv"
    )

    script_entropy_summary_df.to_csv(summary_outpath, index=False)
    print(f"Saved batch summary -> {summary_outpath}")


# （可选）合并所有 seed 的 summary
all_summary_df = pd.concat(script_entropy_summary_all, ignore_index=True)

all_summary_outpath = (
    f"{out_root}/{model_name}/{space_name}/"
    f"random/script_entropy_all_seeds.csv"
)

all_summary_df.to_csv(all_summary_outpath, index=False)
print(f"\nSaved merged summary -> {all_summary_outpath}")

===== Running seed 0 =====

=== Running random script entropy: seed=0, pca_dim=5 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=0, pca_dim=142 ===

=== Running random script entropy: seed=0, pca_dim=997 ===

=== Running random script entropy: seed=0, pca_dim=2084 ===

=== Running random script entropy: seed=0, pca_dim=3031 ===

=== Running random script entropy: seed=0, pca_dim=3459 ===

=== Running random script entropy: seed=0, pca_dim=3938 ===

=== Running random script entropy: seed=0, pca_dim=4088 ===

=== Running random script entropy: seed=0, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_0/summary_random_pca_seed_0_script_entropy.csv

===== Running seed 42 =====

=== Running random script entropy: seed=42, pca_dim=5 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=42, pca_dim=142 ===

=== Running random script entropy: seed=42, pca_dim=997 ===

=== Running random script entropy: seed=42, pca_dim=2084 ===

=== Running random script entropy: seed=42, pca_dim=3031 ===

=== Running random script entropy: seed=42, pca_dim=3459 ===

=== Running random script entropy: seed=42, pca_dim=3938 ===

=== Running random script entropy: seed=42, pca_dim=4088 ===

=== Running random script entropy: seed=42, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_42/summary_random_pca_seed_42_script_entropy.csv

===== Running seed 1000 =====

=== Running random script entropy: seed=1000, pca_dim=5 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=1000, pca_dim=142 ===

=== Running random script entropy: seed=1000, pca_dim=997 ===

=== Running random script entropy: seed=1000, pca_dim=2084 ===

=== Running random script entropy: seed=1000, pca_dim=3031 ===

=== Running random script entropy: seed=1000, pca_dim=3459 ===

=== Running random script entropy: seed=1000, pca_dim=3938 ===

=== Running random script entropy: seed=1000, pca_dim=4088 ===

=== Running random script entropy: seed=1000, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1000/summary_random_pca_seed_1000_script_entropy.csv

===== Running seed 9999 =====

=== Running random script entropy: seed=9999, pca_dim=5 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=9999, pca_dim=142 ===

=== Running random script entropy: seed=9999, pca_dim=997 ===

=== Running random script entropy: seed=9999, pca_dim=2084 ===

=== Running random script entropy: seed=9999, pca_dim=3031 ===

=== Running random script entropy: seed=9999, pca_dim=3459 ===

=== Running random script entropy: seed=9999, pca_dim=3938 ===

=== Running random script entropy: seed=9999, pca_dim=4088 ===

=== Running random script entropy: seed=9999, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_9999/summary_random_pca_seed_9999_script_entropy.csv

===== Running seed 1813382118 =====

=== Running random script entropy: seed=1813382118, pca_dim=5 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=1813382118, pca_dim=142 ===

=== Running random script entropy: seed=1813382118, pca_dim=997 ===

=== Running random script entropy: seed=1813382118, pca_dim=2084 ===

=== Running random script entropy: seed=1813382118, pca_dim=3031 ===

=== Running random script entropy: seed=1813382118, pca_dim=3459 ===

=== Running random script entropy: seed=1813382118, pca_dim=3938 ===

=== Running random script entropy: seed=1813382118, pca_dim=4088 ===

=== Running random script entropy: seed=1813382118, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_142/partition_script_entropy_summary.json

### Permutation

In [6]:
from script_entropy import run_script_entropy_over_permutation_seeds

permutation_result = run_script_entropy_over_permutation_seeds(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    perm_seed_list=seed_list,
    pca_dim_list=pca_dim_list,
    l2_norm=l2_norm,
    min_cluster_size=min_cluster_size,
    min_samples=min_samples,
    metric=metric,
    cluster_selection_method=cluster_selection_method,
    cluster_selection_epsilon=cluster_selection_epsilon,
    tokenizer=tokenizer,
    cluster_id_col=cluster_id_col,
    token_str_col=token_col,
    print_columns_first_only=False,
)

permutation_result["mean_summary_df"]

Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2084/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2084/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2084/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3031/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3031/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3031/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3459/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3459/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3459/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3938/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3938/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3938/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4088/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4088/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4088/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_5/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_5/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_5/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_142/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_142/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_142/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_997/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_997/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_997/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2084/token_with_script.csv

,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,num_clusters,mean_H,std_H,mean_H_norm,std_H_norm
0,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,5,True,5,5,euclidean,eom,0.0,308,0.617964,0.347857,0.181690,0.102275
1,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,142,True,5,5,euclidean,eom,0.0,79,0.690211,0.314637,0.202932,0.092508
2,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,997,True,5,5,euclidean,eom,0.0,647,0.334087,0.294314,0.098226,0.086532
3,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,2084,True,5,5,euclidean,eom,0.0,883,0.293335,0.276215,0.086245,0.081211
4,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,3031,True,5,5,euclidean,eom,0.0,939,0.269052,0.266114,0.079105,0.078241
5,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,3459,True,5,5,euclidean,eom,0.0,953,0.217943,0.242677,0.064078,0.071350
6,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,3938,True,5,5,euclidean,eom,0.0,968,0.222403,0.247319,0.065389,0.072715
7,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,4088,True,5,5,euclidean,eom,0.0,971,0.255329,0.259663,0.075070,0.076345
8,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,4096,True,5,5,euclidean,eom,0.0,983,0.236964,0.251704,0.069671,0.074005

# Mixtral-8x7B

In [7]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "permutation/mistralai/Mixtral-8x7B-v0.1_rand"
space_name = "output_proj"

# out_root = "comp"
# model_name = "mistralai/Mixtral-8x7B-v0.1"
# space_name = "output_proj"

# ===== Step 1: Load tokenizer =====
tokenizer_path = f"mistralai/Mixtral-8x7B-v0.1/tokenizer" 
tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
print(f"[✓] Tokenizer loaded from: {tokenizer_path}")


l2_norm = True
min_cluster_size = 5
min_samples = 5
metric = "euclidean"
cluster_selection_method = "eom"
cluster_selection_epsilon = 0.0

token_col = "token_str"
cluster_id_col = "cluster_id"

pca_dim_list = [8, 158, 1111, 2156, 3052, 3457, 3957, 4093, 4096]

[✓] Tokenizer loaded from: mistralai/Mixtral-8x7B-v0.1/tokenizer

In [26]:
batch_result = run_script_entropy_over_pca_dims(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    pca_dim_list=pca_dim_list,
    l2_norm=l2_norm,
    min_cluster_size=min_cluster_size,
    min_samples=min_samples,
    metric=metric,
    cluster_selection_method=cluster_selection_method,
    cluster_selection_epsilon=cluster_selection_epsilon,
    tokenizer=tokenizer,
    print_columns_first_only=True,
)

=== Running script entropy: pca_dim=8 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running script entropy: pca_dim=158 ===

=== Running script entropy: pca_dim=1111 ===

=== Running script entropy: pca_dim=2156 ===

=== Running script entropy: pca_dim=3052 ===

=== Running script entropy: pca_dim=3457 ===

=== Running script entropy: pca_dim=3957 ===

=== Running script entropy: pca_dim=4093 ===

=== Running script entropy: pca_dim=4096 ===

In [27]:
script_entropy_summary_df = batch_result["summary_df"]
script_entropy_summary_df

,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,num_clusters,mean_H,std_H,mean_H_norm,std_H_norm
0,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,8,True,5,5,euclidean,eom,0.0,87,0.302867,0.274952,0.089047,0.080840
1,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,158,True,5,5,euclidean,eom,0.0,228,0.626278,0.271765,0.184135,0.079903
2,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,1111,True,5,5,euclidean,eom,0.0,978,0.270383,0.255159,0.079496,0.075020
3,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,2156,True,5,5,euclidean,eom,0.0,1082,0.264030,0.255015,0.077629,0.074978
4,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,3052,True,5,5,euclidean,eom,0.0,1098,0.258407,0.258169,0.075975,0.075905
5,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,3457,True,5,5,euclidean,eom,0.0,1097,0.275375,0.264162,0.080964,0.077667
6,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,3957,True,5,5,euclidean,eom,0.0,1094,0.311995,0.275141,0.091731,0.080895
7,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,4093,True,5,5,euclidean,eom,0.0,1091,0.309468,0.268353,0.090988,0.078900
8,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,4096,True,5,5,euclidean,eom,0.0,1091,0.306487,0.268249,0.090112,0.078869

In [13]:
script_entropy_summary_df = batch_result["summary_df"]

summary_outpath = (
    f"{out_root}/{model_name}/{space_name}/"
    "script_entropy_summary.csv"
)

script_entropy_summary_df.to_csv(summary_outpath, index=False)
print(f"Saved batch summary -> {summary_outpath}")

Saved batch summary -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy_summary.csv

In [14]:
from script_entropy import save_single_partition_outputs

for pca_dim, result in batch_result["per_partition_results"].items():
    out_dir = (
        f"{out_root}/{model_name}/{space_name}/"
        f"script_entropy/pca_{pca_dim}"
    )

    save_single_partition_outputs(
        result=result,
        out_dir=out_dir,
    )

Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/script_entropy/pca_4096/partition_script_entropy_summary.json

### random

In [23]:
script_entropy_summary_all = []

for pca_seed in seed_list:
    print(f"\n===== Running seed {pca_seed} =====")

    batch_result = run_script_entropy_over_random_pca_dims(
        out_root=out_root,
        model_name=model_name,
        space_name=space_name,
        pca_seed=pca_seed,
        pca_dim_list=pca_dim_list,
        l2_norm=l2_norm,
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        metric=metric,
        cluster_selection_method=cluster_selection_method,
        cluster_selection_epsilon=cluster_selection_epsilon,
        tokenizer=tokenizer,
        print_columns_first_only=True,
    )

    script_entropy_summary_df = batch_result["summary_df"]
    script_entropy_summary_all.append(script_entropy_summary_df)


    for pca_dim, result in batch_result["per_partition_results"].items():
        out_dir = (
            f"{out_root}/{model_name}/{space_name}/"
            f"random/seed_{pca_seed}/"
            f"script_entropy/pca_{pca_dim}"
        )

        save_single_partition_outputs(
            result=result,
            out_dir=out_dir,
        )

    summary_outpath = (
        f"{out_root}/{model_name}/{space_name}/"
        f"random/seed_{pca_seed}/"
        f"summary_random_pca_seed_{pca_seed}_script_entropy.csv"
    )

    script_entropy_summary_df.to_csv(summary_outpath, index=False)
    print(f"Saved batch summary -> {summary_outpath}")


# （可选）合并所有 seed 的 summary
all_summary_df = pd.concat(script_entropy_summary_all, ignore_index=True)

all_summary_outpath = (
    f"{out_root}/{model_name}/{space_name}/"
    f"random/script_entropy_all_seeds.csv"
)

all_summary_df.to_csv(all_summary_outpath, index=False)
print(f"\nSaved merged summary -> {all_summary_outpath}")

===== Running seed 0 =====

=== Running random script entropy: seed=0, pca_dim=8 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=0, pca_dim=158 ===

=== Running random script entropy: seed=0, pca_dim=1111 ===

=== Running random script entropy: seed=0, pca_dim=2156 ===

=== Running random script entropy: seed=0, pca_dim=3052 ===

=== Running random script entropy: seed=0, pca_dim=3457 ===

=== Running random script entropy: seed=0, pca_dim=3957 ===

=== Running random script entropy: seed=0, pca_dim=4093 ===

=== Running random script entropy: seed=0, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_0/summary_random_pca_seed_0_script_entropy.csv

===== Running seed 42 =====

=== Running random script entropy: seed=42, pca_dim=8 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=42, pca_dim=158 ===

=== Running random script entropy: seed=42, pca_dim=1111 ===

=== Running random script entropy: seed=42, pca_dim=2156 ===

=== Running random script entropy: seed=42, pca_dim=3052 ===

=== Running random script entropy: seed=42, pca_dim=3457 ===

=== Running random script entropy: seed=42, pca_dim=3957 ===

=== Running random script entropy: seed=42, pca_dim=4093 ===

=== Running random script entropy: seed=42, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_42/summary_random_pca_seed_42_script_entropy.csv

===== Running seed 1000 =====

=== Running random script entropy: seed=1000, pca_dim=8 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=1000, pca_dim=158 ===

=== Running random script entropy: seed=1000, pca_dim=1111 ===

=== Running random script entropy: seed=1000, pca_dim=2156 ===

=== Running random script entropy: seed=1000, pca_dim=3052 ===

=== Running random script entropy: seed=1000, pca_dim=3457 ===

=== Running random script entropy: seed=1000, pca_dim=3957 ===

=== Running random script entropy: seed=1000, pca_dim=4093 ===

=== Running random script entropy: seed=1000, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1000/summary_random_pca_seed_1000_script_entropy.csv

===== Running seed 9999 =====

=== Running random script entropy: seed=9999, pca_dim=8 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=9999, pca_dim=158 ===

=== Running random script entropy: seed=9999, pca_dim=1111 ===

=== Running random script entropy: seed=9999, pca_dim=2156 ===

=== Running random script entropy: seed=9999, pca_dim=3052 ===

=== Running random script entropy: seed=9999, pca_dim=3457 ===

=== Running random script entropy: seed=9999, pca_dim=3957 ===

=== Running random script entropy: seed=9999, pca_dim=4093 ===

=== Running random script entropy: seed=9999, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_9999/summary_random_pca_seed_9999_script_entropy.csv

===== Running seed 1813382118 =====

=== Running random script entropy: seed=1813382118, pca_dim=8 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=1813382118, pca_dim=158 ===

=== Running random script entropy: seed=1813382118, pca_dim=1111 ===

=== Running random script entropy: seed=1813382118, pca_dim=2156 ===

=== Running random script entropy: seed=1813382118, pca_dim=3052 ===

=== Running random script entropy: seed=1813382118, pca_dim=3457 ===

=== Running random script entropy: seed=1813382118, pca_dim=3957 ===

=== Running random script entropy: seed=1813382118, pca_dim=4093 ===

=== Running random script entropy: seed=1813382118, pca_dim=4096 ===
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/mistralai/Mixtral-8x7B-v0.1/output_proj/random/seed_1813382118/script_entropy/pca_158/token_with_script.csv

### Permutation

In [8]:
from script_entropy import run_script_entropy_over_permutation_seeds

permutation_result = run_script_entropy_over_permutation_seeds(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    perm_seed_list=seed_list,
    pca_dim_list=pca_dim_list,
    l2_norm=l2_norm,
    min_cluster_size=min_cluster_size,
    min_samples=min_samples,
    metric=metric,
    cluster_selection_method=cluster_selection_method,
    cluster_selection_epsilon=cluster_selection_epsilon,
    tokenizer=tokenizer,
    cluster_id_col=cluster_id_col,
    token_str_col=token_col,
    print_columns_first_only=False,
)

permutation_result["mean_summary_df"]

Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1813382118/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_827307999/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1627694678/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_1111/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2156/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2156/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2156/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3052/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3052/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3052/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3457/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3457/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3457/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3957/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3957/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_3957/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4093/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4093/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4093/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4096/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4096/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_1911784257/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_8/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_8/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_8/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_158/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_158/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_158/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_1111/token_with_script.csv
Saved cluster-level output -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_1111/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/seeds/seed_903170602/script_entropy/pca_1111/partition_script_entropy_summary.json

,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,num_clusters,mean_H,std_H,mean_H_norm,std_H_norm
0,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,8,True,5,5,euclidean,eom,0.0,87,0.305920,0.271839,0.089945,0.079925
1,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,158,True,5,5,euclidean,eom,0.0,228,0.613605,0.264446,0.180409,0.077751
2,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,1111,True,5,5,euclidean,eom,0.0,978,0.269958,0.258714,0.079371,0.076066
3,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,2156,True,5,5,euclidean,eom,0.0,1082,0.264030,0.254978,0.077628,0.074967
4,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,3052,True,5,5,euclidean,eom,0.0,1098,0.261390,0.255287,0.076852,0.075058
5,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,3457,True,5,5,euclidean,eom,0.0,1097,0.272121,0.259367,0.080007,0.076258
6,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,3957,True,5,5,euclidean,eom,0.0,1094,0.310862,0.269803,0.091398,0.079326
7,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,4093,True,5,5,euclidean,eom,0.0,1091,0.310556,0.269885,0.091308,0.079350
8,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,4096,True,5,5,euclidean,eom,0.0,1091,0.309390,0.269371,0.090965,0.079199

# gpt-oss-20B

In [5]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "permutation/gpt-oss_rand"
space_name = "output_proj"

# out_root = "comp"
# model_name = "gpt-oss"
# space_name = "output_proj"

# ===== Step 1: Load tokenizer =====
tokenizer_path = f"gpt-oss/tokenizer" 
tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
print(f"[✓] Tokenizer loaded from: {tokenizer_path}")


l2_norm = True
min_cluster_size = 5
min_samples = 5
metric = "euclidean"
cluster_selection_method = "eom"
cluster_selection_epsilon = 0.0

token_col = "token_str"
cluster_id_col = "cluster_id"

pca_dim_list = [6, 182, 466, 739, 1591, 2264, 2532, 2868, 2880]

[✓] Tokenizer loaded from: gpt-oss/tokenizer

In [29]:
batch_result = run_script_entropy_over_pca_dims(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    pca_dim_list=pca_dim_list,
    l2_norm=l2_norm,
    min_cluster_size=min_cluster_size,
    min_samples=min_samples,
    metric=metric,
    cluster_selection_method=cluster_selection_method,
    cluster_selection_epsilon=cluster_selection_epsilon,
    tokenizer=tokenizer,
    print_columns_first_only=True,
)

=== Running script entropy: pca_dim=6 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running script entropy: pca_dim=182 ===

=== Running script entropy: pca_dim=466 ===

=== Running script entropy: pca_dim=739 ===

=== Running script entropy: pca_dim=1591 ===

=== Running script entropy: pca_dim=2264 ===

=== Running script entropy: pca_dim=2532 ===

=== Running script entropy: pca_dim=2868 ===

=== Running script entropy: pca_dim=2880 ===

In [30]:
script_entropy_summary_df = batch_result["summary_df"]
script_entropy_summary_df

,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,num_clusters,mean_H,std_H,mean_H_norm,std_H_norm
0,permutation/gpt-oss_rand,output_proj,6,True,5,5,euclidean,eom,0.0,1203,0.160877,0.207236,0.232096,0.298978
1,permutation/gpt-oss_rand,output_proj,182,True,5,5,euclidean,eom,0.0,740,0.404922,0.217191,0.584179,0.313340
2,permutation/gpt-oss_rand,output_proj,466,True,5,5,euclidean,eom,0.0,1941,0.275935,0.216407,0.398090,0.312209
3,permutation/gpt-oss_rand,output_proj,739,True,5,5,euclidean,eom,0.0,2783,0.193127,0.191926,0.278624,0.276890
4,permutation/gpt-oss_rand,output_proj,1591,True,5,5,euclidean,eom,0.0,3625,0.143438,0.166976,0.206937,0.240895
5,permutation/gpt-oss_rand,output_proj,2264,True,5,5,euclidean,eom,0.0,3819,0.145206,0.169384,0.209487,0.244369
6,permutation/gpt-oss_rand,output_proj,2532,True,5,5,euclidean,eom,0.0,3856,0.141912,0.167175,0.204736,0.241183
7,permutation/gpt-oss_rand,output_proj,2868,True,5,5,euclidean,eom,0.0,3880,0.139249,0.166585,0.200894,0.240331
8,permutation/gpt-oss_rand,output_proj,2880,True,5,5,euclidean,eom,0.0,3880,0.141887,0.167420,0.204700,0.241536

In [18]:
script_entropy_summary_df = batch_result["summary_df"]

summary_outpath = (
    f"{out_root}/{model_name}/{space_name}/"
    "script_entropy_summary.csv"
)

script_entropy_summary_df.to_csv(summary_outpath, index=False)
print(f"Saved batch summary -> {summary_outpath}")

Saved batch summary -> comp/permutation/gpt-oss_rand/output_proj/script_entropy_summary.csv

In [20]:
from script_entropy import save_single_partition_outputs

for pca_dim, result in batch_result["per_partition_results"].items():
    out_dir = (
        f"{out_root}/{model_name}/{space_name}/"
        f"script_entropy/pca_{pca_dim}"
    )

    save_single_partition_outputs(
        result=result,
        out_dir=out_dir,
    )

Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/script_entropy/pca_2880/partition_script_entropy_summary.json

In [25]:
script_entropy_summary_all = []

for pca_seed in seed_list:
    print(f"\n===== Running seed {pca_seed} =====")

    batch_result = run_script_entropy_over_random_pca_dims(
        out_root=out_root,
        model_name=model_name,
        space_name=space_name,
        pca_seed=pca_seed,
        pca_dim_list=pca_dim_list,
        l2_norm=l2_norm,
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        metric=metric,
        cluster_selection_method=cluster_selection_method,
        cluster_selection_epsilon=cluster_selection_epsilon,
        tokenizer=tokenizer,
        print_columns_first_only=True,
    )

    script_entropy_summary_df = batch_result["summary_df"]
    script_entropy_summary_all.append(script_entropy_summary_df)


    for pca_dim, result in batch_result["per_partition_results"].items():
        out_dir = (
            f"{out_root}/{model_name}/{space_name}/"
            f"random/seed_{pca_seed}/"
            f"script_entropy/pca_{pca_dim}"
        )

        save_single_partition_outputs(
            result=result,
            out_dir=out_dir,
        )

    summary_outpath = (
        f"{out_root}/{model_name}/{space_name}/"
        f"random/seed_{pca_seed}/"
        f"summary_random_pca_seed_{pca_seed}_script_entropy.csv"
    )

    script_entropy_summary_df.to_csv(summary_outpath, index=False)
    print(f"Saved batch summary -> {summary_outpath}")


# （可选）合并所有 seed 的 summary
all_summary_df = pd.concat(script_entropy_summary_all, ignore_index=True)

all_summary_outpath = (
    f"{out_root}/{model_name}/{space_name}/"
    f"random/script_entropy_all_seeds.csv"
)

all_summary_df.to_csv(all_summary_outpath, index=False)
print(f"\nSaved merged summary -> {all_summary_outpath}")

===== Running seed 0 =====

=== Running random script entropy: seed=0, pca_dim=6 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=0, pca_dim=182 ===

=== Running random script entropy: seed=0, pca_dim=466 ===

=== Running random script entropy: seed=0, pca_dim=739 ===

=== Running random script entropy: seed=0, pca_dim=1591 ===

=== Running random script entropy: seed=0, pca_dim=2264 ===

=== Running random script entropy: seed=0, pca_dim=2532 ===

=== Running random script entropy: seed=0, pca_dim=2868 ===

=== Running random script entropy: seed=0, pca_dim=2880 ===
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_0/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/gpt-oss/output_proj/random/seed_0/summary_random_pca_seed_0_script_entropy.csv

===== Running seed 42 =====

=== Running random script entropy: seed=42, pca_dim=6 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=42, pca_dim=182 ===

=== Running random script entropy: seed=42, pca_dim=466 ===

=== Running random script entropy: seed=42, pca_dim=739 ===

=== Running random script entropy: seed=42, pca_dim=1591 ===

=== Running random script entropy: seed=42, pca_dim=2264 ===

=== Running random script entropy: seed=42, pca_dim=2532 ===

=== Running random script entropy: seed=42, pca_dim=2868 ===

=== Running random script entropy: seed=42, pca_dim=2880 ===
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_42/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/gpt-oss/output_proj/random/seed_42/summary_random_pca_seed_42_script_entropy.csv

===== Running seed 1000 =====

=== Running random script entropy: seed=1000, pca_dim=6 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=1000, pca_dim=182 ===

=== Running random script entropy: seed=1000, pca_dim=466 ===

=== Running random script entropy: seed=1000, pca_dim=739 ===

=== Running random script entropy: seed=1000, pca_dim=1591 ===

=== Running random script entropy: seed=1000, pca_dim=2264 ===

=== Running random script entropy: seed=1000, pca_dim=2532 ===

=== Running random script entropy: seed=1000, pca_dim=2868 ===

=== Running random script entropy: seed=1000, pca_dim=2880 ===
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1000/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/gpt-oss/output_proj/random/seed_1000/summary_random_pca_seed_1000_script_entropy.csv

===== Running seed 9999 =====

=== Running random script entropy: seed=9999, pca_dim=6 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=9999, pca_dim=182 ===

=== Running random script entropy: seed=9999, pca_dim=466 ===

=== Running random script entropy: seed=9999, pca_dim=739 ===

=== Running random script entropy: seed=9999, pca_dim=1591 ===

=== Running random script entropy: seed=9999, pca_dim=2264 ===

=== Running random script entropy: seed=9999, pca_dim=2532 ===

=== Running random script entropy: seed=9999, pca_dim=2868 ===

=== Running random script entropy: seed=9999, pca_dim=2880 ===
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_9999/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/gpt-oss/output_proj/random/seed_9999/summary_random_pca_seed_9999_script_entropy.csv

===== Running seed 1813382118 =====

=== Running random script entropy: seed=1813382118, pca_dim=6 ===
cluster_df.columns = ['token_id', 'cluster_id', 'probability']

=== Running random script entropy: seed=1813382118, pca_dim=182 ===

=== Running random script entropy: seed=1813382118, pca_dim=466 ===

=== Running random script entropy: seed=1813382118, pca_dim=739 ===

=== Running random script entropy: seed=1813382118, pca_dim=1591 ===

=== Running random script entropy: seed=1813382118, pca_dim=2264 ===

=== Running random script entropy: seed=1813382118, pca_dim=2532 ===

=== Running random script entropy: seed=1813382118, pca_dim=2868 ===

=== Running random script entropy: seed=1813382118, pca_dim=2880 ===
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/gpt-oss/output_proj/random/seed_1813382118/script_entropy/pca_2868/token_with_script.csv

### Permutation

In [6]:
from script_entropy import run_script_entropy_over_permutation_seeds

permutation_result = run_script_entropy_over_permutation_seeds(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    perm_seed_list=seed_list,
    pca_dim_list=pca_dim_list,
    l2_norm=l2_norm,
    min_cluster_size=min_cluster_size,
    min_samples=min_samples,
    metric=metric,
    cluster_selection_method=cluster_selection_method,
    cluster_selection_epsilon=cluster_selection_epsilon,
    tokenizer=tokenizer,
    cluster_id_col=cluster_id_col,
    token_str_col=token_col,
    print_columns_first_only=False,
)

permutation_result["mean_summary_df"]

Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1813382118/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_827307999/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1627694678/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2880/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2880/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy/pca_2880/partition_script_entropy_summary.json
Saved batch summary -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_1911784257/script_entropy_summary.csv
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_6/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_6/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_6/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_182/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_182/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_182/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_466/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_466/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_466/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_739/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_739/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_739/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_1591/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_1591/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_1591/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2264/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2264/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2264/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2532/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2532/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2532/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2868/token_with_script.csv
Saved cluster-level output -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2868/cluster_script_entropy.csv
Saved summary output       -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2868/partition_script_entropy_summary.json
Saved token-level output   -> comp/permutation/gpt-oss_rand/output_proj/seeds/seed_903170602/script_entropy/pca_2880/token_with_script.csv

,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,num_clusters,mean_H,std_H,mean_H_norm,std_H_norm
0,permutation/gpt-oss_rand,output_proj,6,True,5,5,euclidean,eom,0.0,1203,0.159792,0.205209,0.230531,0.296054
1,permutation/gpt-oss_rand,output_proj,182,True,5,5,euclidean,eom,0.0,740,0.409874,0.211542,0.591323,0.305191
2,permutation/gpt-oss_rand,output_proj,466,True,5,5,euclidean,eom,0.0,1941,0.278649,0.217240,0.402005,0.313412
3,permutation/gpt-oss_rand,output_proj,739,True,5,5,euclidean,eom,0.0,2783,0.190274,0.190940,0.274507,0.275469
4,permutation/gpt-oss_rand,output_proj,1591,True,5,5,euclidean,eom,0.0,3625,0.141060,0.167590,0.203507,0.241782
5,permutation/gpt-oss_rand,output_proj,2264,True,5,5,euclidean,eom,0.0,3819,0.145810,0.169510,0.210360,0.244551
6,permutation/gpt-oss_rand,output_proj,2532,True,5,5,euclidean,eom,0.0,3856,0.141077,0.168031,0.203530,0.242417
7,permutation/gpt-oss_rand,output_proj,2868,True,5,5,euclidean,eom,0.0,3880,0.139588,0.167028,0.201384,0.240970
8,permutation/gpt-oss_rand,output_proj,2880,True,5,5,euclidean,eom,0.0,3880,0.140075,0.166826,0.202086,0.240680

### Length-bucket permutation script entropy

In [ ]:
from transformers import AutoTokenizer
from script_entropy import run_script_entropy_over_permutation_seeds


length_bucket_seed_list = [
    86939546,
    827307999,
    1627694678,
    1813382118,
    1911784257,
    903170602,
    556019485,
    2073320061,
    1097954097,
    1043521778,
]

length_bucket_script_configs = [
    {
        "label": "mistral",
        "model_name": "permutation/mistralai/Mistral-7B-v0.1_length_bucket_rand",
        "tokenizer_path": "mistralai/Mistral-7B-v0.1/tokenizer",
        "pca_dim_list": [5, 142, 997, 2084, 3031, 3459, 3938, 4088, 4096],
    },
    {
        "label": "mixtral",
        "model_name": "permutation/mistralai/Mixtral-8x7B-v0.1_length_bucket_rand",
        "tokenizer_path": "mistralai/Mixtral-8x7B-v0.1/tokenizer",
        "pca_dim_list": [8, 158, 1111, 2156, 3052, 3457, 3957, 4093, 4096],
    },
    {
        "label": "gpt-oss",
        "model_name": "permutation/gpt-oss_length_bucket_rand",
        "tokenizer_path": "gpt-oss/tokenizer",
        "pca_dim_list": [6, 182, 466, 739, 1591, 2264, 2532, 2868, 2880],
    },
]

length_bucket_script_results = {}

for config in length_bucket_script_configs:
    print(f"\n===== Running length-bucket script entropy: {config['label']} =====")
    tokenizer = AutoTokenizer.from_pretrained(config["tokenizer_path"])
    result = run_script_entropy_over_permutation_seeds(
        out_root="comp",
        model_name=config["model_name"],
        space_name="output_proj",
        perm_seed_list=length_bucket_seed_list,
        pca_dim_list=config["pca_dim_list"],
        l2_norm=True,
        min_cluster_size=5,
        min_samples=5,
        metric="euclidean",
        cluster_selection_method="eom",
        cluster_selection_epsilon=0.0,
        tokenizer=tokenizer,
        print_columns_first_only=True,
    )
    length_bucket_script_results[config["label"]] = result

length_bucket_script_results["gpt-oss"]["mean_summary_df"]

# Random Orthogonal Projection Script Entropy Analysis

In [7]:
from pathlib import Path

import pandas as pd
from transformers import AutoTokenizer

from random_projection import DEFAULT_SEEDS, MODEL_CONFIGS
from script_entropy import (
    aggregate_permutation_script_means,
    build_global_script_cache_from_tokenizer,
    run_script_entropy_for_partition,
    save_batch_summary_df,
    save_single_partition_outputs,
)


def run_random_projection_script_entropy_for_model(
    model_key,
    *,
    out_root="comp",
    space_name="output_proj",
    seed_list=DEFAULT_SEEDS,
):
    model_config = MODEL_CONFIGS[model_key]
    model_name = model_config["model_name"]
    pca_dim_list = model_config["candidate_dims"]
    tokenizer = AutoTokenizer.from_pretrained(model_config["tokenizer_path"])
    script_cache = build_global_script_cache_from_tokenizer(
        tokenizer,
        model_name=model_name,
    )
    global_script_set = script_cache["global_script_set"]
    random_projection_dir = Path(out_root) / model_name / space_name / "random_projection"
    per_seed_results = {}
    all_seed_rows = []

    for rp_seed in seed_list:
        seed_dir = random_projection_dir / f"seed_{int(rp_seed)}"
        summary_df = pd.read_csv(seed_dir / "summary.csv")
        rows = []
        per_partition_results = {}

        for pca_dim in pca_dim_list:
            part_result = run_script_entropy_for_partition(
                summary_df=summary_df,
                out_root=out_root,
                model_name=model_name,
                space_name=space_name,
                pca_dim=int(pca_dim),
                l2_norm=True,
                min_cluster_size=5,
                min_samples=5,
                metric="euclidean",
                cluster_selection_method="eom",
                cluster_selection_epsilon=0.0,
                tokenizer=tokenizer,
                global_script_set=global_script_set,
                print_columns=False,
            )
            stats = part_result["partition_stats"]
            rows.append({
                "model_name": model_name,
                "space_name": space_name,
                "rp_seed": int(rp_seed),
                "pca_dim": int(pca_dim),
                "l2_norm": True,
                "min_cluster_size": 5,
                "min_samples": 5,
                "metric": "euclidean",
                "cluster_selection_method": "eom",
                "cluster_selection_epsilon": 0.0,
                "num_clusters": stats["num_clusters"],
                "mean_H": stats["mean_H"],
                "std_H": stats["std_H"],
                "mean_H_norm": stats["mean_H_norm"],
                "std_H_norm": stats["std_H_norm"],
            })
            per_partition_results[int(pca_dim)] = part_result
            save_single_partition_outputs(
                result=part_result,
                out_dir=seed_dir / "script_entropy" / f"pca_dim_{int(pca_dim)}",
            )

        seed_summary_df = pd.DataFrame(rows).sort_values("pca_dim").reset_index(drop=True)
        save_batch_summary_df(
            summary_df=seed_summary_df,
            out_path=seed_dir / "script_entropy_summary.csv",
        )
        per_seed_results[int(rp_seed)] = {
            "summary_df": seed_summary_df,
            "per_partition_results": per_partition_results,
        }
        all_seed_rows.append(seed_summary_df)

    all_seed_summary_df = pd.concat(all_seed_rows, axis=0, ignore_index=True)
    all_seed_summary_df = all_seed_summary_df.sort_values(
        ["rp_seed", "pca_dim"]
    ).reset_index(drop=True)
    mean_summary_df = aggregate_permutation_script_means(all_seed_summary_df)
    save_batch_summary_df(
        summary_df=all_seed_summary_df,
        out_path=random_projection_dir / "script_entropy_summary_all_seeds.csv",
    )
    save_batch_summary_df(
        summary_df=mean_summary_df,
        out_path=random_projection_dir / "script_entropy_summary_mean.csv",
    )
    return {
        "script_cache": script_cache,
        "per_seed_results": per_seed_results,
        "all_seed_summary_df": all_seed_summary_df,
        "mean_summary_df": mean_summary_df,
    }

In [8]:
random_projection_script_results = {}
for model_key in ["mistral", "mixtral", "gpt-oss"]:
    random_projection_script_results[model_key] = (
        run_random_projection_script_entropy_for_model(model_key)
    )

random_projection_script_results["gpt-oss"]["mean_summary_df"]

Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_5/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_142/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_997/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_2084/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_3031/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_3459/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_3938/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_4088/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy/pca_dim_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1813382118/script_entropy_summary.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_5/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_142/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_997/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_2084/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_3031/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_3459/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_3938/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_4088/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy/pca_dim_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_827307999/script_entropy_summary.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_5/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_142/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_997/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_2084/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_3031/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_3459/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_3938/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_4088/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy/pca_dim_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1627694678/script_entropy_summary.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_5/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_142/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_997/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_2084/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_3031/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_3459/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_3938/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_4088/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy/pca_dim_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_1911784257/script_entropy_summary.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_5/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_142/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_997/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_2084/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_3031/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_3459/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_3938/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_4088/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy/pca_dim_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_903170602/script_entropy_summary.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_5/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_142/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_997/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_2084/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_2084/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_3031/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_3031/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_3459/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_3459/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_3938/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_3938/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_4088/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_4088/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_4096/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy/pca_dim_4096/partition_script_entropy_summary.json
Saved batch summary -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_86939546/script_entropy_summary.csv
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/script_entropy/pca_dim_5/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/script_entropy/pca_dim_5/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/script_entropy/pca_dim_142/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/script_entropy/pca_dim_142/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/script_entropy/pca_dim_997/cluster_script_entropy.csv
Saved summary output       -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/script_entropy/pca_dim_997/partition_script_entropy_summary.json
Saved cluster-level output -> comp/mistralai/Mistral-7B-v0.1/output_proj/random_projection/seed_556019485/script_entropy/pca_dim_2084/cluster_script_entropy.csv

,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,num_clusters,mean_H,std_H,mean_H_norm,std_H_norm
0,gpt-oss,output_proj,6,True,5,5,euclidean,eom,0.0,3259,0.876101,0.429090,0.260179,0.127429
1,gpt-oss,output_proj,182,True,5,5,euclidean,eom,0.0,3345,0.305709,0.432566,0.090788,0.128461
2,gpt-oss,output_proj,466,True,5,5,euclidean,eom,0.0,3680,0.308427,0.442198,0.091595,0.131321
3,gpt-oss,output_proj,739,True,5,5,euclidean,eom,0.0,3768,0.308856,0.443771,0.091722,0.131788
4,gpt-oss,output_proj,1591,True,5,5,euclidean,eom,0.0,3859,0.309601,0.446767,0.091943,0.132678
5,gpt-oss,output_proj,2264,True,5,5,euclidean,eom,0.0,3864,0.308825,0.444957,0.091713,0.132141
6,gpt-oss,output_proj,2532,True,5,5,euclidean,eom,0.0,3863,0.309877,0.446083,0.092025,0.132475
7,gpt-oss,output_proj,2868,True,5,5,euclidean,eom,0.0,3875,0.309712,0.447572,0.091976,0.132917
8,gpt-oss,output_proj,2880,True,5,5,euclidean,eom,0.0,3877,0.310698,0.448107,0.092269,0.133076