In [11]:
import pandas as pd
from pathlib import Path
import sys

sys.path.append("./cluster_anlys")

from pearson import (
    run_seed_pearson_analysis,
    run_pearson_over_random_seeds,
    save_pearson_summary_df,
    make_main_pearson_latex_table,
    make_appendix_pearson_latex_table,
    make_permutation_vs_full_latex_table,
)

from pearson import (
    load_full_morphology_summary,
    load_full_script_summary,
    standardize_morphology_summary_df,
    standardize_script_summary_df,
    compare_seed_to_baseline_for_metric,
    compare_seed_to_baseline_joint_mean,
)

seed_list = [0, 42, 1000, 9999,1813382118, 827307999, 1627694678, 1911784257]

In [2]:
seed_list = [1813382118,
 827307999,
 1627694678,
 1911784257,
 903170602,
 86939546,
 556019485,
 2073320061,
 1097954097,
 1043521778]

# gpt-oss

In [12]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "gpt-oss"
space_name = "output_proj"


# Increase this for final reporting.
n_permutations = 5000
random_state = 0

In [13]:
# Run one seed first as a sanity check.
single_seed_df = run_seed_pearson_analysis(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    seed=1000,
    n_permutations=n_permutations,
    random_state=random_state,
)
single_seed_df

,seed,n_dims_morph,morph_mean_r,morph_mean_p,morph_std_r,morph_std_p,morph_mean_std_joint_r,morph_mean_std_joint_perm_p,n_dims_script,script_mean_r,script_mean_p,script_std_r,script_std_p,script_mean_std_joint_r,script_mean_std_joint_perm_p,n_dims_joint_mean,joint_mean_r,joint_mean_perm_p,model_name,space_name
0,1000,9,0.998592,3.444506e-10,0.991228,2.063653e-07,0.999799,0.0002,9,0.998987,1.088134e-10,0.999093,7.381601e-11,0.999781,0.0002,9,0.998748,0.0002,gpt-oss,output_proj

In [14]:
# Run all seeds.
gpt_oss_pearson_summary_df = run_pearson_over_random_seeds(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    seed_list=seed_list,
    n_permutations=n_permutations,
    random_state=random_state,
)

gpt_oss_pearson_summary_df

,seed,n_dims_morph,morph_mean_r,morph_mean_p,morph_std_r,morph_std_p,morph_mean_std_joint_r,morph_mean_std_joint_perm_p,n_dims_script,script_mean_r,script_mean_p,script_std_r,script_std_p,script_mean_std_joint_r,script_mean_std_joint_perm_p,n_dims_joint_mean,joint_mean_r,joint_mean_perm_p,model_name,space_name
0,0,9,0.999699,1.553526e-12,0.994193,4.884770e-08,0.999943,0.0002,9,0.998712,2.522984e-10,0.997517,2.506595e-09,0.999427,0.0002,9,0.999076,0.0002,gpt-oss,output_proj
1,42,9,0.999499,9.250118e-12,0.986307,9.760020e-07,0.999913,0.0002,9,0.998298,6.679349e-10,0.998207,8.015821e-10,0.999592,0.0002,9,0.998668,0.0002,gpt-oss,output_proj
2,1000,9,0.998592,3.444506e-10,0.991228,2.063653e-07,0.999799,0.0002,9,0.998987,1.088134e-10,0.999093,7.381601e-11,0.999781,0.0002,9,0.998748,0.0002,gpt-oss,output_proj
3,9999,9,0.999633,3.129332e-12,0.991873,1.580779e-07,0.999272,0.0002,9,0.999315,2.769175e-11,0.998023,1.128835e-09,0.996354,0.0002,9,0.985176,0.0002,gpt-oss,output_proj
4,1813382118,9,0.999810,3.086230e-13,0.996830,5.888239e-09,0.999963,0.0002,9,0.998772,2.135300e-10,0.997879,1.444971e-09,0.999427,0.0002,9,0.999018,0.0002,gpt-oss,output_proj
5,827307999,9,0.999319,2.713918e-11,0.992188,1.376627e-07,0.999574,0.0002,9,0.998292,6.766467e-10,0.998349,6.012829e-10,0.998754,0.0002,9,0.993575,0.0002,gpt-oss,output_proj
6,1627694678,9,0.999625,3.351255e-12,0.991435,1.898661e-07,0.999894,0.0002,9,0.998875,1.571158e-10,0.998988,1.085706e-10,0.999482,0.0002,9,0.998899,0.0002,gpt-oss,output_proj
7,1911784257,9,0.999553,6.212818e-12,0.995331,2.278769e-08,0.999887,0.0002,9,0.997839,1.540262e-09,0.998459,4.721918e-10,0.999228,0.0002,9,0.996910,0.0002,gpt-oss,output_proj

In [15]:
# Save summary CSV.
outpath = Path(out_root) / model_name / space_name / "pearson_summary.csv"
save_pearson_summary_df(gpt_oss_pearson_summary_df, outpath)
print(outpath)

comp/gpt-oss/output_proj/pearson_summary.csv

In [16]:
# Optional: select only the primary analysis columns.
primary_cols = [
    "seed",
    "morph_mean_r",
    "morph_mean_p",
    "script_mean_r",
    "script_mean_p",
    "joint_mean_r",
    "joint_mean_perm_p",
]

gpt_oss_pearson_summary_df[primary_cols].sort_values("seed").reset_index(drop=True)

,seed,morph_mean_r,morph_mean_p,script_mean_r,script_mean_p,joint_mean_r,joint_mean_perm_p
0,0,0.999699,1.553526e-12,0.998712,2.522984e-10,0.999076,0.0002
1,42,0.999499,9.250118e-12,0.998298,6.679349e-10,0.998668,0.0002
2,1000,0.998592,3.444506e-10,0.998987,1.088134e-10,0.998748,0.0002
3,9999,0.999633,3.129332e-12,0.999315,2.769175e-11,0.985176,0.0002
4,827307999,0.999319,2.713918e-11,0.998292,6.766467e-10,0.993575,0.0002
5,1627694678,0.999625,3.351255e-12,0.998875,1.571158e-10,0.998899,0.0002
6,1813382118,0.999810,3.086230e-13,0.998772,2.135300e-10,0.999018,0.0002
7,1911784257,0.999553,6.212818e-12,0.997839,1.540262e-09,0.996910,0.0002

# Mistral-7B

In [17]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "mistralai/Mistral-7B-v0.1"
space_name = "output_proj"

n_permutations = 5000
random_state = 0

In [18]:
mistral_pearson_summary_df = run_pearson_over_random_seeds(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    seed_list=seed_list,
    n_permutations=n_permutations,
    random_state=random_state,
)

mistral_pearson_summary_df

,seed,n_dims_morph,morph_mean_r,morph_mean_p,morph_std_r,morph_std_p,morph_mean_std_joint_r,morph_mean_std_joint_perm_p,n_dims_script,script_mean_r,script_mean_p,script_std_r,script_std_p,script_mean_std_joint_r,script_mean_std_joint_perm_p,n_dims_joint_mean,joint_mean_r,joint_mean_perm_p,model_name,space_name
0,0,9,0.999348,2.331172e-11,0.984357,1.552678e-06,0.999614,0.0006,9,0.996673,6.969073e-09,0.989985,3.277649e-07,0.993707,0.0002,9,0.996922,0.0002,mistralai/Mistral-7B-v0.1,output_proj
1,42,9,0.998346,6.043618e-10,0.993910,5.768448e-08,0.999341,0.0002,9,0.992417,1.241286e-07,0.992750,1.060711e-07,0.991466,0.0002,9,0.992488,0.0002,mistralai/Mistral-7B-v0.1,output_proj
2,1000,9,0.997915,1.359721e-09,0.989994,3.267335e-07,0.999491,0.0002,9,0.999308,2.873381e-11,0.998620,3.206898e-10,0.998256,0.0002,9,0.997946,0.0002,mistralai/Mistral-7B-v0.1,output_proj
3,9999,9,0.999315,2.766364e-11,0.972758,1.069858e-05,0.999123,0.0006,9,0.998522,4.076300e-10,0.998731,2.390918e-10,0.998067,0.0002,9,0.998089,0.0002,mistralai/Mistral-7B-v0.1,output_proj
4,1813382118,9,0.999360,2.186432e-11,0.989310,4.115049e-07,0.999855,0.0002,9,0.998285,6.869414e-10,0.995892,1.457677e-08,0.996117,0.0004,9,0.996718,0.0002,mistralai/Mistral-7B-v0.1,output_proj
5,827307999,9,0.999401,1.732547e-11,0.983847,1.736048e-06,0.999552,0.0004,9,0.998103,9.767913e-10,0.996604,7.486512e-09,0.997744,0.0002,9,0.998610,0.0002,mistralai/Mistral-7B-v0.1,output_proj
6,1627694678,9,0.998932,1.308316e-10,0.994217,4.816026e-08,0.999743,0.0002,9,0.999710,1.362508e-12,0.998858,1.656239e-10,0.999168,0.0002,9,0.999165,0.0002,mistralai/Mistral-7B-v0.1,output_proj
7,1911784257,9,0.996791,6.143499e-09,0.996943,5.185973e-09,0.999345,0.0002,9,0.998372,5.728506e-10,0.998784,2.060071e-10,0.998298,0.0002,9,0.996266,0.0002,mistralai/Mistral-7B-v0.1,output_proj

In [19]:
outpath = Path(out_root) / model_name / space_name / "pearson_summary.csv"
save_pearson_summary_df(mistral_pearson_summary_df, outpath)
print(outpath)

comp/mistralai/Mistral-7B-v0.1/output_proj/pearson_summary.csv

# Mixtral-8x7B

In [20]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "mistralai/Mixtral-8x7B-v0.1"
space_name = "output_proj"

n_permutations = 5000
random_state = 0

In [21]:
mixtral_pearson_summary_df = run_pearson_over_random_seeds(
    out_root=out_root,
    model_name=model_name,
    space_name=space_name,
    seed_list=seed_list,
    n_permutations=n_permutations,
    random_state=random_state,
)

mixtral_pearson_summary_df

,seed,n_dims_morph,morph_mean_r,morph_mean_p,morph_std_r,morph_std_p,morph_mean_std_joint_r,morph_mean_std_joint_perm_p,n_dims_script,script_mean_r,script_mean_p,script_std_r,script_std_p,script_mean_std_joint_r,script_mean_std_joint_perm_p,n_dims_joint_mean,joint_mean_r,joint_mean_perm_p,model_name,space_name
0,0,9,0.999840,1.689223e-13,0.997073,4.454665e-09,0.999744,0.0004,9,0.999080,7.758622e-11,0.992476,1.207462e-07,0.998071,0.0002,9,0.998546,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
1,42,9,0.999925,1.221136e-14,0.977759,5.286080e-06,0.999834,0.0002,9,0.998138,9.158737e-10,0.997384,3.008214e-09,0.994022,0.0002,9,0.998732,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
2,1000,9,0.999808,3.255212e-13,0.952630,7.271363e-05,0.999414,0.0002,9,0.999345,2.366048e-11,0.993278,8.146381e-08,0.994821,0.0002,9,0.998951,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
3,9999,9,0.999734,1.007295e-12,0.983446,1.890905e-06,0.999467,0.0002,9,0.994484,4.081895e-08,0.995655,1.773294e-08,0.994562,0.0002,9,0.994033,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
4,1813382118,9,0.999878,6.546651e-14,0.988789,4.859197e-07,0.999839,0.0002,9,0.986627,8.988456e-07,0.959327,4.293400e-05,0.985427,0.0002,9,0.992887,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
5,827307999,9,0.999866,9.226014e-14,0.988479,5.344916e-07,0.999907,0.0002,9,0.999040,9.014744e-11,0.998191,8.269118e-10,0.996440,0.0002,9,0.998865,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
6,1627694678,9,0.999959,1.399470e-15,0.991027,2.234126e-07,0.999925,0.0002,9,0.988599,5.151740e-07,0.998771,2.142666e-10,0.995357,0.0002,9,0.994039,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
7,1911784257,9,0.999944,4.326484e-15,0.993931,5.700442e-08,0.999908,0.0002,9,0.976000,6.887970e-06,0.925810,3.403985e-04,0.944372,0.0002,9,0.986489,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj

In [22]:
outpath = Path(out_root) / model_name / space_name / "pearson_summary.csv"
save_pearson_summary_df(mixtral_pearson_summary_df, outpath)
print(outpath)

comp/mistralai/Mixtral-8x7B-v0.1/output_proj/pearson_summary.csv

# Summary

In [23]:
# Combine all model-level results for paper tables.
all_pearson_summary_df = pd.concat(
    [
        gpt_oss_pearson_summary_df,
        mistral_pearson_summary_df,
        mixtral_pearson_summary_df,
    ],
    axis=0,
    ignore_index=True,
)

all_pearson_summary_df

,seed,n_dims_morph,morph_mean_r,morph_mean_p,morph_std_r,morph_std_p,morph_mean_std_joint_r,morph_mean_std_joint_perm_p,n_dims_script,script_mean_r,script_mean_p,script_std_r,script_std_p,script_mean_std_joint_r,script_mean_std_joint_perm_p,n_dims_joint_mean,joint_mean_r,joint_mean_perm_p,model_name,space_name
0,0,9,0.999699,1.553526e-12,0.994193,4.884770e-08,0.999943,0.0002,9,0.998712,2.522984e-10,0.997517,2.506595e-09,0.999427,0.0002,9,0.999076,0.0002,gpt-oss,output_proj
1,42,9,0.999499,9.250118e-12,0.986307,9.760020e-07,0.999913,0.0002,9,0.998298,6.679349e-10,0.998207,8.015821e-10,0.999592,0.0002,9,0.998668,0.0002,gpt-oss,output_proj
2,1000,9,0.998592,3.444506e-10,0.991228,2.063653e-07,0.999799,0.0002,9,0.998987,1.088134e-10,0.999093,7.381601e-11,0.999781,0.0002,9,0.998748,0.0002,gpt-oss,output_proj
3,9999,9,0.999633,3.129332e-12,0.991873,1.580779e-07,0.999272,0.0002,9,0.999315,2.769175e-11,0.998023,1.128835e-09,0.996354,0.0002,9,0.985176,0.0002,gpt-oss,output_proj
4,1813382118,9,0.999810,3.086230e-13,0.996830,5.888239e-09,0.999963,0.0002,9,0.998772,2.135300e-10,0.997879,1.444971e-09,0.999427,0.0002,9,0.999018,0.0002,gpt-oss,output_proj
5,827307999,9,0.999319,2.713918e-11,0.992188,1.376627e-07,0.999574,0.0002,9,0.998292,6.766467e-10,0.998349,6.012829e-10,0.998754,0.0002,9,0.993575,0.0002,gpt-oss,output_proj
6,1627694678,9,0.999625,3.351255e-12,0.991435,1.898661e-07,0.999894,0.0002,9,0.998875,1.571158e-10,0.998988,1.085706e-10,0.999482,0.0002,9,0.998899,0.0002,gpt-oss,output_proj
7,1911784257,9,0.999553,6.212818e-12,0.995331,2.278769e-08,0.999887,0.0002,9,0.997839,1.540262e-09,0.998459,4.721918e-10,0.999228,0.0002,9,0.996910,0.0002,gpt-oss,output_proj
8,0,9,0.999348,2.331172e-11,0.984357,1.552678e-06,0.999614,0.0006,9,0.996673,6.969073e-09,0.989985,3.277649e-07,0.993707,0.0002,9,0.996922,0.0002,mistralai/Mistral-7B-v0.1,output_proj
9,42,9,0.998346,6.043618e-10,0.993910,5.768448e-08,0.999341,0.0002,9,0.992417,1.241286e-07,0.992750,1.060711e-07,0.991466,0.0002,9,0.992488,0.0002,mistralai/Mistral-7B-v0.1,output_proj
10,1000,9,0.997915,1.359721e-09,0.989994,3.267335e-07,0.999491,0.0002,9,0.999308,2.873381e-11,0.998620,3.206898e-10,0.998256,0.0002,9,0.997946,0.0002,mistralai/Mistral-7B-v0.1,output_proj
11,9999,9,0.999315,2.766364e-11,0.972758,1.069858e-05,0.999123,0.0006,9,0.998522,4.076300e-10,0.998731,2.390918e-10,0.998067,0.0002,9,0.998089,0.0002,mistralai/Mistral-7B-v0.1,output_proj
12,1813382118,9,0.999360,2.186432e-11,0.989310,4.115049e-07,0.999855,0.0002,9,0.998285,6.869414e-10,0.995892,1.457677e-08,0.996117,0.0004,9,0.996718,0.0002,mistralai/Mistral-7B-v0.1,output_proj
13,827307999,9,0.999401,1.732547e-11,0.983847,1.736048e-06,0.999552,0.0004,9,0.998103,9.767913e-10,0.996604,7.486512e-09,0.997744,0.0002,9,0.998610,0.0002,mistralai/Mistral-7B-v0.1,output_proj
14,1627694678,9,0.998932,1.308316e-10,0.994217,4.816026e-08,0.999743,0.0002,9,0.999710,1.362508e-12,0.998858,1.656239e-10,0.999168,0.0002,9,0.999165,0.0002,mistralai/Mistral-7B-v0.1,output_proj
15,1911784257,9,0.996791,6.143499e-09,0.996943,5.185973e-09,0.999345,0.0002,9,0.998372,5.728506e-10,0.998784,2.060071e-10,0.998298,0.0002,9,0.996266,0.0002,mistralai/Mistral-7B-v0.1,output_proj
16,0,9,0.999840,1.689223e-13,0.997073,4.454665e-09,0.999744,0.0004,9,0.999080,7.758622e-11,0.992476,1.207462e-07,0.998071,0.0002,9,0.998546,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
17,42,9,0.999925,1.221136e-14,0.977759,5.286080e-06,0.999834,0.0002,9,0.998138,9.158737e-10,0.997384,3.008214e-09,0.994022,0.0002,9,0.998732,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
18,1000,9,0.999808,3.255212e-13,0.952630,7.271363e-05,0.999414,0.0002,9,0.999345,2.366048e-11,0.993278,8.146381e-08,0.994821,0.0002,9,0.998951,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
19,9999,9,0.999734,1.007295e-12,0.983446,1.890905e-06,0.999467,0.0002,9,0.994484,4.081895e-08,0.995655,1.773294e-08,0.994562,0.0002,9,0.994033,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
20,1813382118,9,0.999878,6.546651e-14,0.988789,4.859197e-07,0.999839,0.0002,9,0.986627,8.988456e-07,0.959327,4.293400e-05,0.985427,0.0002,9,0.992887,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
21,827307999,9,0.999866,9.226014e-14,0.988479,5.344916e-07,0.999907,0.0002,9,0.999040,9.014744e-11,0.998191,8.269118e-10,0.996440,0.0002,9,0.998865,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
22,1627694678,9,0.999959,1.399470e-15,0.991027,2.234126e-07,0.999925,0.0002,9,0.988599,5.151740e-07,0.998771,2.142666e-10,0.995357,0.0002,9,0.994039,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj
23,1911784257,9,0.999944,4.326484e-15,0.993931,5.700442e-08,0.999908,0.0002,9,0.976000,6.887970e-06,0.925810,3.403985e-04,0.944372,0.0002,9,0.986489,0.0002,mistralai/Mixtral-8x7B-v0.1,output_proj

In [24]:
# Main paper table: seed-level results aggregated into mean ± std by model.
main_table_latex = make_main_pearson_latex_table(
    all_pearson_summary_df,
    precision=3,
    model_order=[
        "gpt-oss",
        "mistralai/Mistral-7B-v0.1",
        "mistralai/Mixtral-8x7B-v0.1",
    ],
    caption="Main Pearson stability results across random PCA seeds.",
    label="tab:pearson_main",
)

print(main_table_latex)

\begin{table}
\caption{Main Pearson stability results across random PCA seeds.}
\label{tab:pearson_main}
\begin{tabular}{lrlll}
\toprule
Model & Seeds & Morph Mean $r$ & Script Mean $r$ & Joint Mean $r$ \\
\midrule
gpt-oss & 8 & 0.999 $\pm$ 0.000 & 0.999 $\pm$ 0.000 & 0.996 $\pm$ 0.005 \\
Mistral-7B & 8 & 0.999 $\pm$ 0.001 & 0.998 $\pm$ 0.002 & 0.997 $\pm$ 0.002 \\
Mixtral-8x7B & 8 & 1.000 $\pm$ 0.000 & 0.993 $\pm$ 0.008 & 0.995 $\pm$ 0.004 \\
\bottomrule
\end{tabular}
\end{table}

In [25]:
# Appendix table: full seed-level results.
appendix_table_latex = make_appendix_pearson_latex_table(
    all_pearson_summary_df,
    precision=3,
    model_order=[
        "gpt-oss",
        "mistralai/Mistral-7B-v0.1",
        "mistralai/Mixtral-8x7B-v0.1",
    ],
    caption="Full seed-level Pearson results.",
    label="tab:pearson_appendix",
    longtable=True,
)

print(appendix_table_latex)

\begin{longtable}{lrllllllllllllll}
\caption{Full seed-level Pearson results.} \label{tab:pearson_appendix} \\
\toprule
Model & Seed & Morph Mean $r$ & Morph Mean $p$ & Script Mean $r$ & Script Mean $p$ & Joint Mean $r$ & Joint Mean Perm. $p$ & Morph Std $r$ & Morph Std $p$ & Script Std $r$ & Script Std $p$ & Morph Mean+Std $r$ & Morph Mean+Std Perm. $p$ & Script Mean+Std $r$ & Script Mean+Std Perm. $p$ \\
\midrule
\endfirsthead
\caption[]{Full seed-level Pearson results.} \\
\toprule
Model & Seed & Morph Mean $r$ & Morph Mean $p$ & Script Mean $r$ & Script Mean $p$ & Joint Mean $r$ & Joint Mean Perm. $p$ & Morph Std $r$ & Morph Std $p$ & Script Std $r$ & Script Std $p$ & Morph Mean+Std $r$ & Morph Mean+Std Perm. $p$ & Script Mean+Std $r$ & Script Mean+Std Perm. $p$ \\
\midrule
\endhead
\midrule
\multicolumn{16}{r}{Continued on next page} \\
\midrule
\endfoot
\bottomrule
\endlastfoot
gpt-oss & 0 & 1.000 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.994 & 0.000 & 0.998 & 0.000 & 1.000 & 0.000 & 0.999 & 0.000 \\
gpt-oss & 42 & 0.999 & 0.000 & 0.998 & 0.000 & 0.999 & 0.000 & 0.986 & 0.000 & 0.998 & 0.000 & 1.000 & 0.000 & 1.000 & 0.000 \\
gpt-oss & 1000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.991 & 0.000 & 0.999 & 0.000 & 1.000 & 0.000 & 1.000 & 0.000 \\
gpt-oss & 9999 & 1.000 & 0.000 & 0.999 & 0.000 & 0.985 & 0.000 & 0.992 & 0.000 & 0.998 & 0.000 & 0.999 & 0.000 & 0.996 & 0.000 \\
gpt-oss & 827307999 & 0.999 & 0.000 & 0.998 & 0.000 & 0.994 & 0.000 & 0.992 & 0.000 & 0.998 & 0.000 & 1.000 & 0.000 & 0.999 & 0.000 \\
gpt-oss & 1627694678 & 1.000 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.991 & 0.000 & 0.999 & 0.000 & 1.000 & 0.000 & 0.999 & 0.000 \\
gpt-oss & 1813382118 & 1.000 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.997 & 0.000 & 0.998 & 0.000 & 1.000 & 0.000 & 0.999 & 0.000 \\
gpt-oss & 1911784257 & 1.000 & 0.000 & 0.998 & 0.000 & 0.997 & 0.000 & 0.995 & 0.000 & 0.998 & 0.000 & 1.000 & 0.000 & 0.999 & 0.000 \\
Mistral-7B & 0 & 0.999 & 0.000 & 0.997 & 0.000 & 0.997 & 0.000 & 0.984 & 0.000 & 0.990 & 0.000 & 1.000 & 0.001 & 0.994 & 0.000 \\
Mistral-7B & 42 & 0.998 & 0.000 & 0.992 & 0.000 & 0.992 & 0.000 & 0.994 & 0.000 & 0.993 & 0.000 & 0.999 & 0.000 & 0.991 & 0.000 \\
Mistral-7B & 1000 & 0.998 & 0.000 & 0.999 & 0.000 & 0.998 & 0.000 & 0.990 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.998 & 0.000 \\
Mistral-7B & 9999 & 0.999 & 0.000 & 0.999 & 0.000 & 0.998 & 0.000 & 0.973 & 0.000 & 0.999 & 0.000 & 0.999 & 0.001 & 0.998 & 0.000 \\
Mistral-7B & 827307999 & 0.999 & 0.000 & 0.998 & 0.000 & 0.999 & 0.000 & 0.984 & 0.000 & 0.997 & 0.000 & 1.000 & 0.000 & 0.998 & 0.000 \\
Mistral-7B & 1627694678 & 0.999 & 0.000 & 1.000 & 0.000 & 0.999 & 0.000 & 0.994 & 0.000 & 0.999 & 0.000 & 1.000 & 0.000 & 0.999 & 0.000 \\
Mistral-7B & 1813382118 & 0.999 & 0.000 & 0.998 & 0.000 & 0.997 & 0.000 & 0.989 & 0.000 & 0.996 & 0.000 & 1.000 & 0.000 & 0.996 & 0.000 \\
Mistral-7B & 1911784257 & 0.997 & 0.000 & 0.998 & 0.000 & 0.996 & 0.000 & 0.997 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.998 & 0.000 \\
Mixtral-8x7B & 0 & 1.000 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.997 & 0.000 & 0.992 & 0.000 & 1.000 & 0.000 & 0.998 & 0.000 \\
Mixtral-8x7B & 42 & 1.000 & 0.000 & 0.998 & 0.000 & 0.999 & 0.000 & 0.978 & 0.000 & 0.997 & 0.000 & 1.000 & 0.000 & 0.994 & 0.000 \\
Mixtral-8x7B & 1000 & 1.000 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.953 & 0.000 & 0.993 & 0.000 & 0.999 & 0.000 & 0.995 & 0.000 \\
Mixtral-8x7B & 9999 & 1.000 & 0.000 & 0.994 & 0.000 & 0.994 & 0.000 & 0.983 & 0.000 & 0.996 & 0.000 & 0.999 & 0.000 & 0.995 & 0.000 \\
Mixtral-8x7B & 827307999 & 1.000 & 0.000 & 0.999 & 0.000 & 0.999 & 0.000 & 0.988 & 0.000 & 0.998 & 0.000 & 1.000 & 0.000 & 0.996 & 0.000 \\
Mixtral-8x7B & 1627694678 & 1.000 & 0.000 & 0.989 & 0.000 & 0.994 & 0.000 & 0.991 & 0.000 & 0.999 & 0.000 & 1.000 & 0.000 & 0.995 & 0.000 \\
Mixtral-8x7B & 1813382118 & 1.000 & 0.000 & 0.987 & 0.000 & 0.993 & 0.000 & 0.989 & 0.000 & 0.959 & 0.000 & 1.000 & 0.000 & 0.985 & 0.000 \\
Mixtral-8x7B & 1911784257 & 1.000 & 0.000 & 0.976 & 0.000 & 0.986 & 0.000 & 0.994 & 0.000 & 0.926 & 0.000 & 1.000 & 0.000 & 0.944 & 0.000 \\
\end{longtable}

# Permutation Vs Full

In [26]:
# Compare each permutation-control model against the original full-PCA baseline.
comparison_specs = [
    # {
    #     "baseline_model_name": "gpt-oss",
    #     "perm_model_name": "permutation/gpt-oss_rand",
    #     "space_name": "output_proj",
    # },
    {
        "baseline_model_name": "mistralai/Mistral-7B-v0.1",
        "perm_model_name": "permutation/mistralai/Mistral-7B-v0.1_rand",
        "space_name": "output_proj",
    },
    {
        "baseline_model_name": "mistralai/Mixtral-8x7B-v0.1",
        "perm_model_name": "permutation/mistralai/Mixtral-8x7B-v0.1_rand",
        "space_name": "output_proj",
    },
]

In [27]:
perm_vs_full_rows = []

for spec in comparison_specs:
    baseline_morph = standardize_morphology_summary_df(
        load_full_morphology_summary(
            out_root="comp",
            model_name=spec["baseline_model_name"],
            space_name=spec["space_name"],
        ),
        df_name="baseline_morphology_summary",
    )
    perm_morph = standardize_morphology_summary_df(
        load_full_morphology_summary(
            out_root="comp",
            model_name=spec["perm_model_name"],
            space_name=spec["space_name"],
            filename="kondrak_global_summary_mean.csv",
        ),
        df_name="permutation_morphology_summary",
    )
    baseline_script = standardize_script_summary_df(
        load_full_script_summary(
            out_root="comp",
            model_name=spec["baseline_model_name"],
            space_name=spec["space_name"],
        ),
        df_name="baseline_script_summary",
    )
    perm_script = standardize_script_summary_df(
        load_full_script_summary(
            out_root="comp",
            model_name=spec["perm_model_name"],
            space_name=spec["space_name"],
            filename="script_entropy_summary_mean.csv",
        ),
        df_name="permutation_script_summary",
    )

    morph_result = compare_seed_to_baseline_for_metric(
        baseline_morph,
        perm_morph,
        metric_family="morph",
        seed=0,
        n_permutations=5000,
        random_state=0,
    )
    script_result = compare_seed_to_baseline_for_metric(
        baseline_script,
        perm_script,
        metric_family="script",
        seed=0,
        n_permutations=5000,
        random_state=0,
    )
    joint_result = compare_seed_to_baseline_joint_mean(
        baseline_morph,
        perm_morph,
        baseline_script,
        perm_script,
        seed=0,
        n_permutations=5000,
        random_state=0,
    )

    perm_vs_full_rows.append({
        "baseline_model_name": spec["baseline_model_name"],
        "perm_model_name": spec["perm_model_name"],
        "morph_mean_r": morph_result["mean_r"],
        "morph_mean_p": morph_result["mean_p"],
        "script_mean_r": script_result["mean_r"],
        "script_mean_p": script_result["mean_p"],
        "joint_mean_r": joint_result["joint_mean_r"],
        "joint_mean_perm_p": joint_result["joint_mean_perm_p"],
        "morph_std_r": morph_result["std_r"],
        "morph_std_p": morph_result["std_p"],
        "script_std_r": script_result["std_r"],
        "script_std_p": script_result["std_p"],
        "morph_mean_std_joint_r": morph_result["mean_std_joint_r"],
        "morph_mean_std_joint_perm_p": morph_result["mean_std_joint_perm_p"],
        "script_mean_std_joint_r": script_result["mean_std_joint_r"],
        "script_mean_std_joint_perm_p": script_result["mean_std_joint_perm_p"],
    })

perm_vs_full_df = pd.DataFrame(perm_vs_full_rows)
perm_vs_full_df

,baseline_model_name,perm_model_name,morph_mean_r,morph_mean_p,script_mean_r,script_mean_p,joint_mean_r,joint_mean_perm_p,morph_std_r,morph_std_p,script_std_r,script_std_p,morph_mean_std_joint_r,morph_mean_std_joint_perm_p,script_mean_std_joint_r,script_mean_std_joint_perm_p
0,mistralai/Mistral-7B-v0.1,permutation/mistralai/Mistral-7B-v0.1_rand,0.883911,0.001564,0.410405,0.272568,0.169676,0.220556,0.902367,0.000869,0.890946,0.001266,0.972826,0.014397,0.165645,0.888622
1,mistralai/Mixtral-8x7B-v0.1,permutation/mistralai/Mixtral-8x7B-v0.1_rand,-0.105626,0.786811,-0.946227,0.000113,-0.320287,0.036793,0.683722,0.042278,0.242254,0.529988,0.872368,0.365727,-0.790531,0.052789

In [28]:
# Primary view for the permutation-control comparison.
perm_vs_full_df[[
    "baseline_model_name",
    "morph_mean_r",
    "morph_mean_p",
    "script_mean_r",
    "script_mean_p",
    "joint_mean_r",
    "joint_mean_perm_p",
]]

,baseline_model_name,morph_mean_r,morph_mean_p,script_mean_r,script_mean_p,joint_mean_r,joint_mean_perm_p
0,mistralai/Mistral-7B-v0.1,0.883911,0.001564,0.410405,0.272568,0.169676,0.220556
1,mistralai/Mixtral-8x7B-v0.1,-0.105626,0.786811,-0.946227,0.000113,-0.320287,0.036793

In [19]:
# LaTeX table for the permutation-vs-full comparison.
perm_vs_full_latex = make_permutation_vs_full_latex_table(
    perm_vs_full_df,
    precision=3,
    model_order=[
        "gpt-oss",
        "mistralai/Mistral-7B-v0.1",
        "mistralai/Mixtral-8x7B-v0.1",
    ],
    caption="Pearson comparison between the original full-PCA results and the permutation control.",
    label="tab:perm_vs_full_pearson",
)

print(perm_vs_full_latex)

\begin{table}
\caption{Pearson comparison between the original full-PCA results and the permutation control.}
\label{tab:perm_vs_full_pearson}
\begin{tabular}{lllllll}
\toprule
Model & Morph Mean $r$ & Morph Mean $p$ & Script Mean $r$ & Script Mean $p$ & Joint Mean $r$ & Joint Mean Perm. $p$ \\
\midrule
gpt-oss & -0.143 & 0.713 & 0.078 & 0.843 & 0.024 & 0.862 \\
Mistral-7B & 0.894 & 0.001 & 0.426 & 0.253 & 0.171 & 0.221 \\
Mixtral-8x7B & -0.114 & 0.771 & -0.946 & 0.000 & -0.329 & 0.039 \\
\bottomrule
\end{tabular}
\end{table}