In [1]:
import pandas as pd
from pathlib import Path
import sys

sys.path.append("./cluster_anlys")

from partition_permutation_control import run_partition_permutation_multi_seed

In [2]:
import random

base_seed = 0
rng = random.Random(base_seed)
seed_list = rng.sample(range(2**31 - 1), 10)
seed_list

[1813382118,
 827307999,
 1627694678,
 1911784257,
 903170602,
 86939546,
 556019485,
 2073320061,
 1097954097,
 1043521778]

In [3]:
seed_list = [1813382118,
 827307999,
 1627694678,
 1911784257,
 903170602,
 86939546,
 556019485,
 2073320061,
 1097954097,
 1043521778]

# gpt-oss

In [4]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "gpt-oss"
fake_model_name = "permutation/gpt-oss_rand"
space_name = "output_proj"

In [5]:
gpt_oss_perm_summary_by_seed, gpt_oss_perm_all_seed_df, gpt_oss_perm_all_seed_path = run_partition_permutation_multi_seed(
    out_root=out_root,
    model_name=model_name,
    fake_model_name=fake_model_name,
    space_name=space_name,
    seed_list=seed_list,
)

print(gpt_oss_perm_all_seed_path)
gpt_oss_perm_all_seed_df.head()

comp/permutation/gpt-oss_rand/output_proj/summary_all_seeds.csv

,run_id,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path,perm_seed
0,1,permutation/gpt-oss_rand,output_proj,6,True,5,5,euclidean,eom,0.0,1203,150324,201088,0.747553,0.247084,0.978759,comp/permutation/gpt-oss_rand/output_proj/seed...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
1,2,permutation/gpt-oss_rand,output_proj,182,True,5,5,euclidean,eom,0.0,740,169765,201088,0.844232,0.144636,0.928540,comp/permutation/gpt-oss_rand/output_proj/seed...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
2,3,permutation/gpt-oss_rand,output_proj,466,True,5,5,euclidean,eom,0.0,1941,168875,201088,0.839806,0.154840,0.966580,comp/permutation/gpt-oss_rand/output_proj/seed...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
3,4,permutation/gpt-oss_rand,output_proj,739,True,5,5,euclidean,eom,0.0,2783,154083,201088,0.766247,0.224960,0.962381,comp/permutation/gpt-oss_rand/output_proj/seed...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
4,5,permutation/gpt-oss_rand,output_proj,1591,True,5,5,euclidean,eom,0.0,3625,135483,201088,0.673750,0.310563,0.951917,comp/permutation/gpt-oss_rand/output_proj/seed...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546

# Mistral-7B

In [18]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "mistralai/Mistral-7B-v0.1"
fake_model_name = "permutation/mistralai/Mistral-7B-v0.1_rand"
space_name = "output_proj"

In [19]:
mistral_perm_summary_by_seed, mistral_perm_all_seed_df, mistral_perm_all_seed_path = run_partition_permutation_multi_seed(
    out_root=out_root,
    model_name=model_name,
    fake_model_name=fake_model_name,
    space_name=space_name,
    seed_list=seed_list,
)

print(mistral_perm_all_seed_path)
mistral_perm_all_seed_df.head()

comp/permutation/mistralai/Mistral-7B-v0.1_rand/output_proj/summary_all_seeds.csv

,run_id,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path,perm_seed
0,1,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,5,True,5,5,euclidean,eom,0.0,308,28275,32000,0.883594,0.109885,0.943976,comp/permutation/mistralai/Mistral-7B-v0.1_ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
1,2,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,142,True,5,5,euclidean,eom,0.0,79,29230,32000,0.913438,0.074777,0.863849,comp/permutation/mistralai/Mistral-7B-v0.1_ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
2,3,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,997,True,5,5,euclidean,eom,0.0,647,24663,32000,0.770719,0.212622,0.927340,comp/permutation/mistralai/Mistral-7B-v0.1_ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
3,4,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,2084,True,5,5,euclidean,eom,0.0,883,22037,32000,0.688656,0.293329,0.942140,comp/permutation/mistralai/Mistral-7B-v0.1_ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
4,5,permutation/mistralai/Mistral-7B-v0.1_rand,output_proj,3031,True,5,5,euclidean,eom,0.0,939,21760,32000,0.680000,0.303131,0.947284,comp/permutation/mistralai/Mistral-7B-v0.1_ran...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546

# Mixtral-8x7B

In [20]:
# =========================================================
# params
# =========================================================
out_root = "comp"
model_name = "mistralai/Mixtral-8x7B-v0.1"
fake_model_name = "permutation/mistralai/Mixtral-8x7B-v0.1_rand"
space_name = "output_proj"

In [21]:
mixtral_perm_summary_by_seed, mixtral_perm_all_seed_df, mixtral_perm_all_seed_path = run_partition_permutation_multi_seed(
    out_root=out_root,
    model_name=model_name,
    fake_model_name=fake_model_name,
    space_name=space_name,
    seed_list=seed_list,
)

print(mixtral_perm_all_seed_path)
mixtral_perm_all_seed_df.head()

comp/permutation/mistralai/Mixtral-8x7B-v0.1_rand/output_proj/summary_all_seeds.csv

,run_id,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path,perm_seed
0,1,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,8,True,5,5,euclidean,eom,0.0,87,23434,32000,0.732313,0.263760,0.985326,comp/permutation/mistralai/Mixtral-8x7B-v0.1_r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
1,2,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,158,True,5,5,euclidean,eom,0.0,228,28034,32000,0.876062,0.118117,0.953040,comp/permutation/mistralai/Mixtral-8x7B-v0.1_r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
2,3,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,1111,True,5,5,euclidean,eom,0.0,978,20304,32000,0.634500,0.344680,0.943036,comp/permutation/mistralai/Mixtral-8x7B-v0.1_r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
3,4,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,2156,True,5,5,euclidean,eom,0.0,1082,19346,32000,0.604563,0.375742,0.950194,comp/permutation/mistralai/Mixtral-8x7B-v0.1_r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
4,5,permutation/mistralai/Mixtral-8x7B-v0.1_rand,output_proj,3052,True,5,5,euclidean,eom,0.0,1098,19362,32000,0.605062,0.376906,0.954343,comp/permutation/mistralai/Mixtral-8x7B-v0.1_r...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546

# Notes

In [22]:
# These fake_model_name values can be passed into the existing metrics pipeline.
pd.DataFrame(
    [
        {"model_name": "permutation/gpt-oss_rand", "summary_path": str(gpt_oss_perm_summary_path)},
        {"model_name": "permutation/mistralai/Mistral-7B-v0.1_rand", "summary_path": str(mistral_perm_summary_path)},
        {"model_name": "permutation/mistralai/Mixtral-8x7B-v0.1_rand", "summary_path": str(mixtral_perm_summary_path)},
    ]
)

NameError: name 'gpt_oss_perm_summary_path' is not defined

# Length-bucketed permutation control

In [4]:
from permutation_multiseed_pipeline import run_length_bucketed_partition_permutation_multi_seed_for_model_key

# gpt-oss length-bucketed

In [5]:
gpt_oss_length_bucket_summary_by_seed, gpt_oss_length_bucket_all_seed_df, gpt_oss_length_bucket_all_seed_path = run_length_bucketed_partition_permutation_multi_seed_for_model_key(
    model_key="gpt-oss",
    seed_list=seed_list,
)

print(gpt_oss_length_bucket_all_seed_path)
gpt_oss_length_bucket_all_seed_df.head()

comp/permutation/gpt-oss_length_bucket_rand/output_proj/summary_all_seeds.csv

,run_id,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path,perm_seed
0,1,permutation/gpt-oss_length_bucket_rand,output_proj,6,True,5,5,euclidean,eom,0.0,1203,150324,201088,0.747553,0.247084,0.978759,comp/permutation/gpt-oss_length_bucket_rand/ou...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
1,2,permutation/gpt-oss_length_bucket_rand,output_proj,182,True,5,5,euclidean,eom,0.0,740,169765,201088,0.844232,0.144636,0.928540,comp/permutation/gpt-oss_length_bucket_rand/ou...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
2,3,permutation/gpt-oss_length_bucket_rand,output_proj,466,True,5,5,euclidean,eom,0.0,1941,168875,201088,0.839806,0.154840,0.966580,comp/permutation/gpt-oss_length_bucket_rand/ou...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
3,4,permutation/gpt-oss_length_bucket_rand,output_proj,739,True,5,5,euclidean,eom,0.0,2783,154083,201088,0.766247,0.224960,0.962381,comp/permutation/gpt-oss_length_bucket_rand/ou...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546
4,5,permutation/gpt-oss_length_bucket_rand,output_proj,1591,True,5,5,euclidean,eom,0.0,3625,135483,201088,0.673750,0.310563,0.951917,comp/permutation/gpt-oss_length_bucket_rand/ou...,comp/gpt-oss/output_proj/meta_l2=True/run_0000...,86939546

# Mistral-7B length-bucketed

In [6]:
mistral_length_bucket_summary_by_seed, mistral_length_bucket_all_seed_df, mistral_length_bucket_all_seed_path = run_length_bucketed_partition_permutation_multi_seed_for_model_key(
    model_key="mistral",
    seed_list=seed_list,
)

print(mistral_length_bucket_all_seed_path)
mistral_length_bucket_all_seed_df.head()

comp/permutation/mistralai/Mistral-7B-v0.1_length_bucket_rand/output_proj/summary_all_seeds.csv

,run_id,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path,perm_seed
0,1,permutation/mistralai/Mistral-7B-v0.1_length_b...,output_proj,5,True,5,5,euclidean,eom,0.0,308,28275,32000,0.883594,0.109885,0.943976,comp/permutation/mistralai/Mistral-7B-v0.1_len...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
1,2,permutation/mistralai/Mistral-7B-v0.1_length_b...,output_proj,142,True,5,5,euclidean,eom,0.0,79,29230,32000,0.913438,0.074777,0.863849,comp/permutation/mistralai/Mistral-7B-v0.1_len...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
2,3,permutation/mistralai/Mistral-7B-v0.1_length_b...,output_proj,997,True,5,5,euclidean,eom,0.0,647,24663,32000,0.770719,0.212622,0.927340,comp/permutation/mistralai/Mistral-7B-v0.1_len...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
3,4,permutation/mistralai/Mistral-7B-v0.1_length_b...,output_proj,2084,True,5,5,euclidean,eom,0.0,883,22037,32000,0.688656,0.293329,0.942140,comp/permutation/mistralai/Mistral-7B-v0.1_len...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546
4,5,permutation/mistralai/Mistral-7B-v0.1_length_b...,output_proj,3031,True,5,5,euclidean,eom,0.0,939,21760,32000,0.680000,0.303131,0.947284,comp/permutation/mistralai/Mistral-7B-v0.1_len...,comp/mistralai/Mistral-7B-v0.1/output_proj/met...,86939546

# Mixtral-8x7B length-bucketed

In [7]:
mixtral_length_bucket_summary_by_seed, mixtral_length_bucket_all_seed_df, mixtral_length_bucket_all_seed_path = run_length_bucketed_partition_permutation_multi_seed_for_model_key(
    model_key="mixtral",
    seed_list=seed_list,
)

print(mixtral_length_bucket_all_seed_path)
mixtral_length_bucket_all_seed_df.head()

comp/permutation/mistralai/Mixtral-8x7B-v0.1_length_bucket_rand/output_proj/summary_all_seeds.csv

,run_id,model_name,space_name,pca_dim,l2_norm,min_cluster_size,min_samples,metric,cluster_selection_method,cluster_selection_epsilon,n_clusters_excl_noise,n_noise,n_total,noise_ratio,avg_prob_all,avg_prob_assigned,cluster_csv_path,meta_json_path,perm_seed
0,1,permutation/mistralai/Mixtral-8x7B-v0.1_length...,output_proj,8,True,5,5,euclidean,eom,0.0,87,23434,32000,0.732313,0.263760,0.985326,comp/permutation/mistralai/Mixtral-8x7B-v0.1_l...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
1,2,permutation/mistralai/Mixtral-8x7B-v0.1_length...,output_proj,158,True,5,5,euclidean,eom,0.0,228,28034,32000,0.876062,0.118117,0.953040,comp/permutation/mistralai/Mixtral-8x7B-v0.1_l...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
2,3,permutation/mistralai/Mixtral-8x7B-v0.1_length...,output_proj,1111,True,5,5,euclidean,eom,0.0,978,20304,32000,0.634500,0.344680,0.943036,comp/permutation/mistralai/Mixtral-8x7B-v0.1_l...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
3,4,permutation/mistralai/Mixtral-8x7B-v0.1_length...,output_proj,2156,True,5,5,euclidean,eom,0.0,1082,19346,32000,0.604563,0.375742,0.950194,comp/permutation/mistralai/Mixtral-8x7B-v0.1_l...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546
4,5,permutation/mistralai/Mixtral-8x7B-v0.1_length...,output_proj,3052,True,5,5,euclidean,eom,0.0,1098,19362,32000,0.605062,0.376906,0.954343,comp/permutation/mistralai/Mixtral-8x7B-v0.1_l...,comp/mistralai/Mixtral-8x7B-v0.1/output_proj/m...,86939546

# Length-bucket token counts

In [8]:
from partition_permutation_control import filter_valid_cluster_df, load_cluster_df, load_summary_df
from permutation_multiseed_pipeline import (
    MODEL_CONFIGS,
    attach_length_bucket_column,
    load_tokenizer_for_model_config,
)

LENGTH_BUCKET_COLUMNS = ["1-2", "3-5", "6-10", "11+"]


def summarize_length_bucket_counts_for_model_key(
    model_key,
    *,
    out_root="comp",
    space_name="output_proj",
):
    model_config = MODEL_CONFIGS[model_key]
    source_model_name = model_config["source_model_name"]
    tokenizer = load_tokenizer_for_model_config(model_config)
    summary_df = load_summary_df(
        out_root=out_root,
        model_name=source_model_name,
        space_name=space_name,
    )
    token_text_cache = {}
    rows = []

    for _, row in summary_df.iterrows():
        cluster_df = load_cluster_df(row["cluster_csv_path"])
        valid_cluster_df = filter_valid_cluster_df(cluster_df)
        bucketed_df = attach_length_bucket_column(
            valid_cluster_df,
            tokenizer=tokenizer,
            model_name=source_model_name,
            token_text_cache=token_text_cache,
        )
        bucket_counts = bucketed_df["length_bucket"].value_counts().to_dict()
        out_row = {
            "model_key": model_key,
            "source_model_name": source_model_name,
            "run_id": int(row["run_id"]),
            "pca_dim": int(row["pca_dim"]),
            "n_non_noise": int(len(bucketed_df)),
        }
        for bucket_name in LENGTH_BUCKET_COLUMNS:
            safe_name = bucket_name.replace("+", "_plus").replace("-", "_")
            out_row[f"count_{safe_name}"] = int(bucket_counts.get(bucket_name, 0))
        rows.append(out_row)

    return pd.DataFrame(rows).sort_values("pca_dim").reset_index(drop=True)

In [9]:
gpt_oss_length_bucket_counts_df = summarize_length_bucket_counts_for_model_key("gpt-oss")
mistral_length_bucket_counts_df = summarize_length_bucket_counts_for_model_key("mistral")
mixtral_length_bucket_counts_df = summarize_length_bucket_counts_for_model_key("mixtral")

length_bucket_counts_df = pd.concat(
    [
        gpt_oss_length_bucket_counts_df,
        mistral_length_bucket_counts_df,
        mixtral_length_bucket_counts_df,
    ],
    axis=0,
    ignore_index=True,
)

length_bucket_counts_outpath = Path("comp") / "permutation" / "length_bucket_token_counts.csv"
length_bucket_counts_outpath.parent.mkdir(parents=True, exist_ok=True)
length_bucket_counts_df.to_csv(length_bucket_counts_outpath, index=False)
print(length_bucket_counts_outpath)
length_bucket_counts_df

comp/permutation/length_bucket_token_counts.csv

,model_key,source_model_name,run_id,pca_dim,n_non_noise,count_1_2,count_3_5,count_6_10,count_11_plus
0,gpt-oss,gpt-oss,1,6,50764,4492,23337,20952,1983
1,gpt-oss,gpt-oss,2,182,31323,7457,13513,9282,1071
2,gpt-oss,gpt-oss,3,466,32213,4749,10910,14069,2485
3,gpt-oss,gpt-oss,4,739,47005,4859,15313,22887,3946
4,gpt-oss,gpt-oss,5,1591,65605,5285,21240,33533,5547
5,gpt-oss,gpt-oss,6,2264,68657,5440,22472,34932,5813
6,gpt-oss,gpt-oss,7,2532,68836,5438,22474,35102,5822
7,gpt-oss,gpt-oss,8,2868,68802,5410,22509,35030,5853
8,gpt-oss,gpt-oss,9,2880,68817,5406,22515,35042,5854
9,mistral,mistralai/Mistral-7B-v0.1,1,5,3725,698,1656,1256,115
10,mistral,mistralai/Mistral-7B-v0.1,2,142,2770,664,1194,868,44
11,mistral,mistralai/Mistral-7B-v0.1,3,997,7337,725,2737,3451,424
12,mistral,mistralai/Mistral-7B-v0.1,4,2084,9963,884,3743,4766,570
13,mistral,mistralai/Mistral-7B-v0.1,5,3031,10240,747,3810,5056,627
14,mistral,mistralai/Mistral-7B-v0.1,6,3459,10157,650,3835,5055,617
15,mistral,mistralai/Mistral-7B-v0.1,7,3938,10284,670,3933,5062,619
16,mistral,mistralai/Mistral-7B-v0.1,8,4088,10714,748,4171,5170,625
17,mistral,mistralai/Mistral-7B-v0.1,9,4096,10605,684,4104,5188,629
18,mixtral,mistralai/Mixtral-8x7B-v0.1,1,8,8566,937,3506,3711,412
19,mixtral,mistralai/Mixtral-8x7B-v0.1,2,158,3966,700,1632,1472,162
20,mixtral,mistralai/Mixtral-8x7B-v0.1,3,1111,11696,915,4525,5579,677
21,mixtral,mistralai/Mixtral-8x7B-v0.1,4,2156,12654,979,4925,6039,711
22,mixtral,mistralai/Mixtral-8x7B-v0.1,5,3052,12638,894,4979,6064,701
23,mixtral,mistralai/Mixtral-8x7B-v0.1,6,3457,12807,930,5059,6115,703
24,mixtral,mistralai/Mixtral-8x7B-v0.1,7,3957,12959,1039,5130,6098,692
25,mixtral,mistralai/Mixtral-8x7B-v0.1,8,4093,12956,991,5160,6113,692
26,mixtral,mistralai/Mixtral-8x7B-v0.1,9,4096,12958,995,5162,6109,692